export const ICON_MAP = {
	classic: {
		theme: {
			Ancient: 'icons/environment/wilderness/carved-standing-stone.webp',
			Corrupted: 'icons/magic/unholy/beam-impact-purple.webp',
			Fortified: 'icons/environment/settlement/watchtower-cliff.webp',
			Hallowed: 'icons/magic/holy/angel-wings-gray.webp',
			Haunted: 'icons/creatures/magical/spirit-undead-horned-blue.webp',
			Infested: 'icons/creatures/eyes/icy-cluster-blue.webp',
			Ravaged: 'icons/environment/settlement/building-rubble.webp',
			Wild: 'icons/magic/nature/root-vines-grow-brown.webp'
		},
		domain: {
			Barrow: 'icons/environment/wilderness/cave-entrance-dwarven-hill.webp',
			Cavern: 'icons/environment/wilderness/cave-entrance-mountain-blue.webp',
			'Frozen cavern': 'icons/magic/water/water-iceberg-bubbles.webp',
			Icereach: 'icons/magic/water/barrier-ice-crystal-wall-jagged-blue.webp',
			Mine: 'icons/environment/settlement/mine-cart-rocks-red.webp',
			Pass: 'icons/environment/wilderness/cave-entrance-rocky.webp',
			Ruin: 'icons/environment/wilderness/wall-ruins.webp',
			'Sea cave': 'icons/environment/wilderness/cave-entrance-island.webp',
			Shadowfen: 'icons/environment/wilderness/cave-entrance.webp',
			Stronghold: 'icons/environment/settlement/castle.webp',
			Tanglewood: 'icons/environment/wilderness/terrain-forest-gray.webp',
			Underkeep: 'icons/environment/wilderness/mine-interior-dungeon-door.webp'
		},
		foe: {
			Broken: 'icons/creatures/mammals/humanoid-fox-cat-archer.webp',
			'Common Folk': 'icons/tools/hand/shovel-spade-steel-blue-brown.webp',
			Hunter: 'icons/environment/people/archer.webp',
			Mystic: 'icons/environment/people/cleric-orange.webp',
			Raider: 'icons/sundries/flags/banner-flag-pirate.webp',
			Warrior: 'icons/skills/melee/hand-grip-sword-red.webp',
			Elf: 'icons/creatures/magical/humanoid-horned-rider.webp',
			Giant: 'icons/creatures/magical/humanoid-giant-forest-blue.webp',
			Primordial: 'icons/creatures/magical/spirit-undead-horned-blue.webp',
			Troll: 'icons/creatures/mammals/bull-horns-eyes-glowin-orange.webp',
			Varou: 'icons/creatures/mammals/wolf-shadow-black.webp',
			Bear: 'icons/creatures/abilities/bear-roar-bite-brown-green.webp',
			Boar: 'icons/commodities/treasure/figurine-boar.webp',
			Gaunt: 'icons/magic/fire/elemental-creature-horse.webp',
			'Marsh Rat': 'icons/creatures/mammals/rodent-rat-diseaed-gray.webp',
			Wolf: 'icons/creatures/abilities/wolf-howl-moon-purple.webp',
			Basilisk: 'icons/creatures/reptiles/snake-poised-white.webp',
			'Elder Beast':
				'icons/creatures/mammals/beast-horned-scaled-glowing-orange.webp',
			'Harrow Spider': 'icons/creatures/invertebrates/spider-web-black.webp',
			Leviathan: 'icons/creatures/reptiles/serpent-horned-green.webp',
			Mammoth: 'icons/commodities/leather/fur-white.webp',
			Wyvern: 'icons/creatures/abilities/wolf-heads-swirl-purple.webp',
			Bonewalker: 'icons/magic/death/undead-skeleton-worn-blue.webp',
			Frostbound: 'icons/creatures/magical/spirit-undead-ghost-blue.webp',
			Chimera: 'icons/creatures/magical/spirit-earth-stone-magma-yellow.webp',
			Haunt: 'icons/magic/death/undead-ghost-strike-white.webp',
			Hollow: 'icons/consumables/plants/grass-leaves-green.webp',
			'Iron Revenant':
				'icons/creatures/magical/construct-golem-stone-blue.webp',
			Sodden: 'icons/magic/death/undead-ghost-scream-teal.webp'
		}
	},
	delve: {
		foe: {
			Bladewing: 'icons/creatures/magical/spirit-undead-winged-ghost.webp',
			'Carrion Newt':
				'icons/creatures/reptiles/chameleon-camouflage-green-brown.webp',
			'Cave Lion': 'icons/creatures/abilities/lion-roar-yellow.webp',
			'Deep Rat': 'icons/creatures/mammals/rodent-rat-green.webp',
			'Nightmare Spider':
				'icons/creatures/invertebrates/spider-mandibles-brown.webp',
			'Shroud Crab':
				'icons/consumables/meat/claw-crab-lobster-serrated-pink.webp',
			Trog: 'icons/creatures/reptiles/lizard-iguana-green.webp',
			'Blood Thorn': 'icons/consumables/plants/thorned-stem-vine-green.webp',
			'Circle of Stones': 'icons/environment/wilderness/arch-stone.webp',
			Glimmer: 'icons/magic/nature/elemental-plant-humanoid.webp',
			Gloom: 'icons/magic/perception/silhouette-stealth-shadow.webp',
			Maelstrom: 'icons/magic/water/vortex-water-whirlpool.webp',
			Tempest: 'icons/magic/lightning/bolts-salvo-clouds-sky.webp',
			Chitter: 'icons/creatures/invertebrates/bug-sixlegged-gray.webp',
			Gnarl: 'icons/magic/nature/tree-animated-strike.webp',
			'Iron-Wracked Beast':
				'icons/environment/wilderness/statue-hound-horned.webp',
			Kraken: 'icons/creatures/fish/squid-kraken-orange.webp',
			Nightspawn: 'icons/creatures/unholy/demon-horned-black-yellow.webp',
			Rhaskar: 'icons/creatures/fish/fish-marlin-swordfight-blue.webp',
			Wyrm: 'icons/creatures/eyes/lizard-single-slit-pink.webp',
			Atanya: 'icons/magic/air/wind-weather-sailing-ship.webp',
			Merrow: 'icons/creatures/fish/fish-man-eye-green.webp',
			Blighthound: 'icons/commodities/treasure/figurine-dog.webp',
			'Bog Rot': 'icons/magic/death/hand-dirt-undead-zombie.webp',
			Bonehorde: 'icons/skills/trades/academics-study-archaeology-bones.webp',
			Thrall: 'icons/creatures/abilities/mouth-teeth-human.webp',
			Wight: 'icons/creatures/magical/humanoid-silhouette-green.webp',
			Husk: 'icons/magic/earth/strike-body-stone-crumble.webp',
			Zealot: 'icons/environment/people/cleric-grey.webp'
		}
	},
	starforged: {
		foe: {
			Chiton: 'icons/creatures/invertebrates/spider-large-white-green.webp',
			'Chiton drone pack':
				'icons/creatures/invertebrates/spider-large-white-green.webp',
			'Chiton queen':
				'icons/creatures/invertebrates/spider-large-white-green.webp',
			Colossus: 'icons/creatures/magical/construct-iron-stomping-yellow.webp',
			'Devotant of the colossi':
				'icons/creatures/magical/construct-iron-stomping-yellow.webp',
			Crystallid: 'icons/magic/water/ice-crystal-white.webp',
			'Convergent crystallid': 'icons/magic/water/ice-crystal-white.webp',
			'Drift pirate': 'icons/skills/trades/profession-sailing-pirate.webp',
			'Pirate boarding party':
				'icons/skills/trades/profession-sailing-pirate.webp',
			'Pirate cutlass': 'icons/skills/trades/profession-sailing-pirate.webp',
			'Ember wisp': 'icons/magic/light/orbs-smoke-pink.webp',
			'Wisp congregation': 'icons/magic/light/orbs-smoke-pink.webp',
			'Firestorm trooper': 'icons/equipment/head/helm-barbute-white.webp',
			'Firestorm raiding team': 'icons/equipment/head/helm-barbute-white.webp',
			'Firestorm dropship': 'icons/equipment/head/helm-barbute-white.webp',
			'Flarewing shark': 'icons/creatures/fish/fish-shark-swimming.webp',
			'Mega flarewing': 'icons/creatures/fish/fish-shark-swimming.webp',
			Ghost: 'icons/creatures/magical/spirit-undead-horned-blue.webp',
			'Ghost ship': 'icons/creatures/magical/spirit-undead-horned-blue.webp',
			Gnawling: 'icons/creatures/mammals/rodent-rat-green.webp',
			'Gnawling brood mother': 'icons/creatures/mammals/rodent-rat-green.webp',
			Howlcat: 'icons/creatures/mammals/cat-hunched-glowing-red.webp',
			'Howlcat pack': 'icons/creatures/mammals/cat-hunched-glowing-red.webp',
			'Iron auger': 'icons/creatures/fish/squid-kraken-orange.webp',
			'Machine mites': 'icons/creatures/fish/squid-kraken-orange.webp',
			'Planet-eater': 'icons/creatures/fish/squid-kraken-orange.webp',
			'Puppet vine': 'icons/magic/nature/plant-vines-skull-green.webp',
			'Flowering puppet vine':
				'icons/magic/nature/plant-vines-skull-green.webp',
			Pyralis: 'icons/creatures/invertebrates/fly-wasp-mosquito-green.webp',
			'Pyralis youngling':
				'icons/creatures/invertebrates/fly-wasp-mosquito-green.webp',
			Risen: 'icons/magic/death/undead-skeleton-rags-fire-green.webp',
			Chimera: 'icons/magic/death/undead-skeleton-rags-fire-green.webp',
			'Scrap bandit': 'icons/equipment/head/hat-belted-simple.webp',
			'Hover prowlers': 'icons/equipment/head/hat-belted-simple.webp',
			'War rig': 'icons/equipment/head/hat-belted-simple.webp',
			Servitor: 'icons/creatures/magical/construct-stone-earth-gray.webp',
			Enforcer: 'icons/creatures/magical/construct-stone-earth-gray.webp',
			Sicklehorn: 'icons/creatures/mammals/goat-horned-blue.webp',
			'Sicklehorn matriarch': 'icons/creatures/mammals/goat-horned-blue.webp',
			'Sicklehorn stampede': 'icons/creatures/mammals/goat-horned-blue.webp',
			'Sky roost': 'icons/magic/nature/root-vine-caduceus-healing.webp',
			'Roost swarm': 'icons/magic/nature/root-vine-caduceus-healing.webp',
			Technoplasm: 'icons/creatures/slimes/slime-movement-pseudopods-blue.webp',
			'Infected bot':
				'icons/creatures/slimes/slime-movement-pseudopods-blue.webp',
			'Scourge ship':
				'icons/creatures/slimes/slime-movement-pseudopods-blue.webp',
			'Void shepherd': 'icons/creatures/fish/fish-bioluminous-blue.webp',
			'Shepherd pod': 'icons/creatures/fish/fish-bioluminous-blue.webp',
			Warden: 'icons/magic/holy/angel-winged-humanoid-blue.webp',
			'Warden cohort': 'icons/magic/holy/angel-winged-humanoid-blue.webp',
			Fury: 'icons/magic/holy/angel-winged-humanoid-blue.webp',
			'Water witcher': 'icons/creatures/mammals/elk-moose-marked-green.webp',
			Dowser: 'icons/creatures/mammals/elk-moose-marked-green.webp',
			Worldbreaker: 'icons/creatures/abilities/mouth-teeth-rows-white.webp',
			'Worldbreaker brood':
				'icons/creatures/abilities/mouth-teeth-rows-white.webp',
			'Elder worm': 'icons/creatures/abilities/mouth-teeth-rows-white.webp'
		},
		asset: {
			Starship: 'systems/foundry-ironsworn/assets/assets/spaceship.svg',
			'Engine Upgrade': 'systems/foundry-ironsworn/assets/assets/rocket-thruster.svg',
			'Expanded Hold': 'systems/foundry-ironsworn/assets/assets/cubeforce.svg',
			Grappler: 'systems/foundry-ironsworn/assets/assets/magnet.svg',
			'Heavy Cannons': 'systems/foundry-ironsworn/assets/assets/ion-cannon-blast.svg',
			'Internal Refit': 'systems/foundry-ironsworn/assets/assets/tinker.svg',
			Medbay: 'systems/foundry-ironsworn/assets/assets/heart-beats.svg',
			'Missile Array': 'systems/foundry-ironsworn/assets/assets/missile-swarm.svg',
			Overseer: 'systems/foundry-ironsworn/assets/assets/eye-target.svg',
			'Reinforced Hull': 'systems/foundry-ironsworn/assets/assets/nested-hexagons.svg',
			'Research Lab': 'systems/foundry-ironsworn/assets/assets/erlenmeyer.svg',
			'Sensor Array': 'systems/foundry-ironsworn/assets/assets/radar-sweep.svg',
			Shields: 'systems/foundry-ironsworn/assets/assets/forward-field.svg',
			'Stealth Tech': 'systems/foundry-ironsworn/assets/assets/sight-disabled.svg',
			'Vehicle Bay': 'systems/foundry-ironsworn/assets/assets/thrust.svg',
			Workshop: 'systems/foundry-ironsworn/assets/assets/spanner.svg',
			Exosuit: 'systems/foundry-ironsworn/assets/assets/space-suit.svg',
			Hoverbike: 'systems/foundry-ironsworn/assets/assets/aero-bike.svg',
			Rover: 'systems/foundry-ironsworn/assets/assets/apc.svg',
			'Service Pod': 'systems/foundry-ironsworn/assets/assets/apollo-capsule.svg',
			Shuttle: 'systems/foundry-ironsworn/assets/assets/scout-ship.svg',
			Skiff: 'systems/foundry-ironsworn/assets/assets/jetpack.svg',
			'Snub Fighter': 'systems/foundry-ironsworn/assets/assets/starfighter.svg',
			Ace: 'systems/foundry-ironsworn/assets/assets/air-force.svg',
			Archer: 'systems/foundry-ironsworn/assets/assets/arrowhead.svg',
			Armored: 'systems/foundry-ironsworn/assets/assets/samus-helmet.svg',
			Artist: 'systems/foundry-ironsworn/assets/assets/flower-twirl.svg',
			Augmented: 'systems/foundry-ironsworn/assets/assets/healing.svg',
			Bannersworn: 'systems/foundry-ironsworn/assets/assets/flying-flag.svg',
			Blademaster: 'systems/foundry-ironsworn/assets/assets/diamond-hilt.svg',
			'Bounty Hunter': 'systems/foundry-ironsworn/assets/assets/human-target.svg',
			Brawler: 'systems/foundry-ironsworn/assets/assets/fist.svg',
			Courier: 'systems/foundry-ironsworn/assets/assets/jigsaw-box.svg',
			Demolitionist: 'systems/foundry-ironsworn/assets/assets/corner-explosion.svg',
			Devotant: 'systems/foundry-ironsworn/assets/assets/prayer.svg',
			Diplomat: 'systems/foundry-ironsworn/assets/assets/shaking-hands.svg',
			Empath: 'systems/foundry-ironsworn/assets/assets/psychic-waves.svg',
			Explorer: 'systems/foundry-ironsworn/assets/assets/compass.svg',
			Fated: 'systems/foundry-ironsworn/assets/assets/polar-star.svg',
			Firebrand: 'systems/foundry-ironsworn/assets/assets/fire-spell-cast.svg',
			Fugitive: 'systems/foundry-ironsworn/assets/assets/run.svg',
			Gearhead: 'systems/foundry-ironsworn/assets/assets/gears.svg',
			Gunslinger: 'systems/foundry-ironsworn/assets/assets/cowboy-holster.svg',
			Gunner: 'systems/foundry-ironsworn/assets/assets/heavy-bullets.svg',
			Haunted: 'systems/foundry-ironsworn/assets/assets/ghost-ally.svg',
			Healer: 'systems/foundry-ironsworn/assets/assets/heart-plus.svg',
			Infiltrator: 'systems/foundry-ironsworn/assets/assets/hood.svg',
			Kinetic: 'systems/foundry-ironsworn/assets/assets/card-play.svg',
			Leader: 'systems/foundry-ironsworn/assets/assets/beams-aura.svg',
			Looper: 'systems/foundry-ironsworn/assets/assets/infinity.svg',
			'Lore Hunter': 'systems/foundry-ironsworn/assets/assets/open-book.svg',
			Loyalist: 'systems/foundry-ironsworn/assets/assets/cherish.svg',
			Mercenary: 'systems/foundry-ironsworn/assets/assets/eagle-emblem.svg',
			Naturalist: 'systems/foundry-ironsworn/assets/assets/dna1.svg',
			Navigator: 'systems/foundry-ironsworn/assets/assets/path-distance.svg',
			Outcast: 'systems/foundry-ironsworn/assets/assets/person.svg',
			Scavenger: 'systems/foundry-ironsworn/assets/assets/vulture.svg',
			Scoundrel: 'systems/foundry-ironsworn/assets/assets/perspective-dice-six-faces-one.svg',
			Seer: 'systems/foundry-ironsworn/assets/assets/semi-closed-eye.svg',
			Shade: 'systems/foundry-ironsworn/assets/assets/invisible.svg',
			Slayer: 'systems/foundry-ironsworn/assets/assets/ivory-tusks.svg',
			Sleuth: 'systems/foundry-ironsworn/assets/assets/magnifying-glass.svg',
			Sniper: 'systems/foundry-ironsworn/assets/assets/targeted.svg',
			Tech: 'systems/foundry-ironsworn/assets/assets/processor.svg',
			Trader: 'systems/foundry-ironsworn/assets/assets/trade.svg',
			Vestige: 'systems/foundry-ironsworn/assets/assets/two-shadows.svg',
			Veteran: 'systems/foundry-ironsworn/assets/assets/medal.svg',
			Voidborn: 'systems/foundry-ironsworn/assets/assets/galaxy.svg',
			'Weapon Master': 'systems/foundry-ironsworn/assets/assets/duel.svg',
			Banshee: 'systems/foundry-ironsworn/assets/assets/bird-twitter.svg',
			'Combat Bot': 'systems/foundry-ironsworn/assets/assets/circuitry.svg',
			Glowcat: 'systems/foundry-ironsworn/assets/assets/hollow-cat.svg',
			'Protocol Bot': 'systems/foundry-ironsworn/assets/assets/talk.svg',
			Rockhorn: 'systems/foundry-ironsworn/assets/assets/mighty-horn.svg',
			Sidekick: 'systems/foundry-ironsworn/assets/assets/shadow-follower.svg',
			Sprite: 'systems/foundry-ironsworn/assets/assets/butterfly.svg',
			'Survey Bot': 'systems/foundry-ironsworn/assets/assets/digital-trace.svg',
			Symbiote: 'systems/foundry-ironsworn/assets/assets/linked-rings.svg',
			'Utility Bot': 'systems/foundry-ironsworn/assets/assets/big-gear.svg',
			Voidglider: 'systems/foundry-ironsworn/assets/assets/whale-tail.svg',
			Bonded: 'systems/foundry-ironsworn/assets/assets/knot.svg',
			Homesteader: 'systems/foundry-ironsworn/assets/assets/wireframe-globe.svg',
			Marked: 'systems/foundry-ironsworn/assets/assets/stars-stack.svg',
			Oathbreaker: 'systems/foundry-ironsworn/assets/assets/cracked-disc.svg',
			Revenant: 'systems/foundry-ironsworn/assets/assets/skull-mask.svg',
			Survivor: 'systems/foundry-ironsworn/assets/assets/broken-heart.svg',
			Vanguard: 'systems/foundry-ironsworn/assets/assets/vertical-banner.svg'
		}
	}
}
