import type {
	BorderColorProperty,
	BorderRadiusProperty,
	BorderStyleProperty,
	BorderWidthProperty,
	Color,
	ColorProperty,
	DisplayProperty,
	FillProperty,
	OpacityProperty,
	PaddingProperty,
	RotateProperty,
	ScaleProperty,
	StandardLonghandPropertiesHyphen,
	StrokeWidthProperty
} from 'csstype'

import type ironswornIconNames from 'virtual:svg-icons-names'
import type { ExtractPropTypes } from 'vue'
import type FontIcon from './font-icon.vue'
import type IronIcon from './iron-icon.vue'

export function enumHas(enumLike: object, value: string | number) {
	return Object.values(enumLike).includes(value)
}

export interface IconSwitchState {
	/**
	 * The ID of the icon to be used for this state.
	 */
	icon: IconId
	/**
	 * @default ''
	 */
	class?: string[]
	/**
	 * Additional props to be passed to the icon component.
	 */
	props?: this['icon'] extends IronswornIconId ? IronIconState : FontIconState
}

export type IronIconState = Omit<ExtractPropTypes<typeof IronIcon>, 'name'> & {
	class?: string
}

export type FontIconState = Omit<ExtractPropTypes<typeof FontIcon>, 'name'> & {
	class?: string
}

export type IronswornIconName = (typeof ironswornIconNames)[number]

export type IronswornIconId = `ironsworn:${IronswornIconName}`
export type FontAwesomeIconId = `fa:${FontAwesome.Name}`

export type IconId = IronswornIconId | FontAwesomeIconId

export interface IconPropsCommon {
	/**
	 * The name of the icon to use.
	 */
	name: string
	/**
	 * The icon's color.
	 */
	color?: FillProperty | ColorProperty
	/**
	 * The icon's stroke.
	 */
	stroke?: {
		width: StrokeWidthProperty<any> | string
		color: ColorProperty
	}
	/**
	 * The height and width of the icon.
	 * @remarks For simplicity's sake, we render all icons with a 1:1 aspect ratio.
	 * @default 1em
	 */
	size?: string
	label?: string
	role?: string
}

export interface IronIconProps extends IconPropsCommon {
	name: IronswornIconName
	/**
	 * The color to use for the SVG fill property.
	 * @default 'currentColor'
	 */
	color?: FillProperty
	/**
	 * The prefix of the sprite map. You probably don't need to change this.
	 * @default 'ironsworn'
	 */
	prefix?: string
	size?: string
	disabled?: boolean
	stroke?: {
		width: StrokeWidthProperty<any>
		color: ColorProperty
	}
}

export interface FontAwesomeIconProps extends IconPropsCommon {
	/**
	 * @default `span`
	 */
	el?: any
	name: FontAwesome.Name
	family?: FontAwesome.Family
	/**
	 * @remarks FVTT doesn't actually provide the FA6 sharp icons, so this shouldn't be used yet.
	 */
	style?: FontAwesome.Style
	/**
	 * Unlabelled content is inaccessible, and will be rendered indicating as such so that screen readers don't try to read icon font glyphs.
	 *
	 * This can also be omitted if a tooltip or other label is provided for a parent component, like with most buttons.
	 */
	label?: string
	/**
	 * @see
	 */
	border?: boolean
	/**
	 * NYI
	 */
	borderOptions?: FontAwesome.Border.Options
	/**
	 * Rether to render the item at a fixed width.
	 * @default true
	 */
	fw?: boolean // fa-fw
	/**
	 * For duotone icons only.
	 */
	'swap-opacity'?: boolean // fa-swap-opacity
	/**
	 * @see https://fontawesome.com/docs/web/style/lists
	 */
	li?: boolean
	inverse?: boolean
	rotate?: FontAwesome.Rotate
	size?: FontAwesome.Size
	pull?: FontAwesome.Pull
	animation?: FontAwesome.Animation[]
	/**
	 * NYI
	 */
	animationOptions?: FontAwesome.Animation.Options
	/**
	 * Used with {@link FontIconStack}.
	 */
	stack?: 'stack-1x' | 'stack-2x'
}

/* Parse FontAwesome classes into the corresponding props. this is basically so that a theme's CSS variable can be used to set component properties. */
// TODO: This could be ditched if Themes are migrated to e.g. a design-token like format, so that we could pass props objects to the icon rather than strings
export function parseClassesToFaProps(cssClasses: string) {
	const props: Partial<FontAwesomeIconProps> & { class?: string[] } = {}
	cssClasses.split(' ').forEach((clsName) => {
		switch (true) {
			case enumHas(FontAwesome.Style, clsName):
				props.style = clsName as FontAwesome.Style
				break
			case enumHas(FontAwesome.Family, clsName):
				props.family = clsName as FontAwesome.Family
				break
			case enumHas(FontAwesome.Rotate, clsName):
				props.rotate = clsName as FontAwesome.Rotate
				break
			case enumHas(FontAwesome.Animation, clsName):
				if (!props.animation) props.animation = []
				props.animation.push(clsName as FontAwesome.Animation)
				break
			default:
				if (!props.class) props.class = []
				props.class.push(clsName)
				break
		}
	})
	return props
}

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace FontAwesome {
	export enum Style {
		Classic = '',
		Sharp = 'fa-sharp'
	}
	export enum Family {
		Solid = 'fa-solid',
		Regular = 'fa-regular',
		Light = 'fa-light',
		Thin = 'fa-thin',
		Duotone = 'fa-duotone'
	}
	export enum Rotate {
		/**
		 * Rotates an icon 90°
		 */
		'90deg' = 'fa-rotate-90',
		/**
		 * Rotates an icon 180°
		 */
		'180deg' = 'fa-rotate-180',
		/**
		 * Rotates an icon 270°
		 */
		'270deg' = 'fa-rotate-270',
		/**
		 * Rotates an icon by a specific degree - setting an accompanying valid inline value for `--fa-rotate-angle` is required
		 */
		By = 'fa-rotate-by'
	}
	export enum Flip {
		/**
		 * Mirrors an icon horizontally
		 */
		Horizontal = 'fa-flip-horizontal',
		/**
		 * Mirrors an icon vertically
		 */
		Vertical = 'fa-flip-vertical',
		/**
		 * Mirrors an icon both vertically and horizontally
		 */
		Both = 'fa-flip-both'
	}

	export enum Pull {
		Left = 'fa-pull-left',
		/* Pulls an icon by floating it left and applying a margin-right */
		Right = 'fa-pull-right'
		/* Pulls an icon by floating it right and applying a margin-left */
	}

	// eslint-disable-next-line @typescript-eslint/no-namespace

	export interface Options {
		/**
		 * Set Font Awesome icon family
		 */
		'fa-style-family':
			| 'Font Awesome 6 Free'
			| 'Font Awesome 6 Pro'
			| 'Font Awesome 6 Duotone'
			| 'Font Awesome 6 Brands'
			| 'Font Awesome 6 Sharp'
		// Set Font Awesome icon style 	Any valid Font Awesome style weight
		'fa-style': 900 | 400 | 100 | 300
		/**
		 * Set display of an icon 	Any valid CSS display value
		 */
		'fa-display': DisplayProperty
		/**
		 * Set color of an inverted icon 	Any valid CSS color value
		 */
		'fa-inverse': Color
	}
	export enum Animation {
		/**
		 * Makes an icon scale up and down
		 * @remark `--fa-beat-scale`: Set max value that an icon will scale
		 */
		Beat = 'fa-beat',
		/**
		 * Makes an icon visually fade in and out using `opacity`
		 * @remark `--fa-fade-opacity`: Set lowest opacity value an icon will fade to and from
		 */
		Fade = 'fa-fade',
		/**
		 * Combines Beat and Fade
		 * @remark `--fa-beat-fade-opacity`: Set lowest opacity value an icon will fade to and from
		 * @remark `--fa-beat-fade-scale`: Set max value that an icon will scale
		 */
		BeatFade = 'fa-beat-fade',
		/**
		 * Bouncing an icon up and down.
		 * @remark `--fa-bounce-rebound`: Set the amount of rebound an icon has when landing after the jump
		 * @remark `--fa-bounce-height`: Set the max height an icon will jump to when bouncing
		 * @remark `--fa-bounce-start-scale-x`: Set the icon's horizontal distortion ("squish") when starting to bounce
		 * @remark `--fa-bounce-start-scale-y`: Set the icon's vertical distortion ("squish") when starting to bounce
		 * @remark `--fa-bounce-jump-scale-x`: Set the icon's horizontal distortion ("squish") at the top of the jump
		 * @remark `--fa-bounce-jump-scale-y`: Set the icon's vertical distortion ("squish") at the top of the jump
		 * @remark `--fa-bounce-land-scale-x`: Set the icon's horizontal distortion ("squish") when landing after the jump
		 * @remark `--fa-bounce-land-scale-y`: Set the icon's vertical distortion ("squish") when landing after the jump
		 */
		Bounce = 'fa-bounce',
		/**
		 * Makes an icon rotate about the Y axis
		 * @remark `--fa-flip-x`: Set x-coordinate of the vector denoting the axis of rotation (between 0 and 1)
		 * @remark `--fa-flip-y`: Set y-coordinate of the vector denoting the axis of rotation (between 0 and 1)
		 * @remark `--fa-flip-z`: Set z-coordinate of the vector denoting the axis of rotation (between 0 and 1)
		 * @remark `--fa-flip-angle`: Set rotation angle of flip. A positive angle denotes a clockwise rotation, a negative angle a counter-clockwise one.
		 */
		Flip = 'fa-flip',
		/**
		 * Use the `fa-shake` animation to grab attention or note that something is not allowed by shaking an icon back and forth.
		 */
		Shake = 'fa-shake',
		/**
		 * Makes an icon spin 360° clock-wise
		 */
		Spin = 'fa-spin',
		/**
		 * Makes an icon spin 360° clock-wise in 8 incremental steps
		 */
		SpinPulse = 'fa-spin-pulse',
		/**
		 * When used in conjunction with `fa-spin` or `fa-spin-pulse`, makes an icon spin counter-clockwise.
		 */
		SpinReverse = 'fa-spin-reverse'
	}
	// eslint-disable-next-line @typescript-eslint/no-namespace
	export namespace Animation {
		/**
		 * CSS custom properties relevant to FontAwesome animations.
		 */
		export interface Options {
			/**
			 * Set an initial delay for animation
			 * Any valid CSS animation-delay value
			 */
			'--fa-animation-delay': StandardLonghandPropertiesHyphen['animation-delay']
			/**
			 * Set direction for animation
			 * Any valid CSS animation-direction value
			 */
			'--fa-animation-direction': StandardLonghandPropertiesHyphen['animation-direction']
			/**
			 * Set duration for animation
			 * Any valid CSS animation-duration value
			 */
			'--fa-animation-duration': StandardLonghandPropertiesHyphen['animation-duration']
			/**
			 * Set number of iterations for animation
			 */
			'--fa-animation-iteration-count': StandardLonghandPropertiesHyphen['animation-iteration-count']
			/**
			 * Set how the animation progresses through frames
			 */
			'--fa-animation-timing': StandardLonghandPropertiesHyphen['animation-timing-function']

			/**
			 * Set the max value an fa-beat icon will scale
			 * Any valid CSS number value
			 */
			'--fa-beat-scale': ScaleProperty
			/**
			 * Set lowest opacity value an fa-fade icon will fade to
			 * @min 0
			 * @max 1.0
			 */
			'--fa-fade-opacity': OpacityProperty
			/**
			 * Set lowest opacity value an fa-beat-fade icon will fade to and from
			 * @min 0
			 * @max 1.0
			 */
			'--fa-beat-fade-opacity': OpacityProperty
			/**
			 * Set max value that an icon will scale
			 * Set the max value an fa-beat-fade icon will scale
			 */
			'--fa-beat-fade-scale': ScaleProperty
			/**
			 * Set an fa-flip icon's x-coordinate of the vector denoting the axis of rotation
			 * @min 0
			 * @max 1
			 */
			'--fa-flip-x': number
			/**
			 * Set an fa-flip icon'sy-coordinate of the vector denoting the axis of rotation
			 * @min 0
			 * @max 1
			 */
			'--fa-flip-y': number
			/**
			 * Set an fa-flip icon's z-coordinate of the vector denoting the axis of rotation
			 * @min 0
			 * @max 1
			 */
			'--fa-flip-z': number
			/**
			 * Set an fa-flip icon's rotation angle. A positive angle denotes a clockwise rotation, a negative angle a counter-clockwise one.
			 * Any valid CSS angle value
			 */
			'--fa-flip-angle': RotateProperty
		}
	}
	// eslint-disable-next-line @typescript-eslint/no-namespace
	export namespace Border {
		export interface Options {
			/**
			 * Set border color
			 */
			'--fa-border-color': BorderColorProperty

			/**
			 * Set padding around icon
			 */
			'--fa-border-padding': PaddingProperty<any>

			/**
			 * Set border radius
			 */
			'--fa-border-radius': BorderRadiusProperty<any>

			/**
			 * Set border style
			 */
			'--fa-border-style': BorderStyleProperty

			/**
			 * Set border width
			 */
			'--fa-border-width': BorderWidthProperty<any>
		}
	}
	export enum Size {
		/**
		 * Changes an icon's font-size to 1em
		 */
		'1x' = 'fa-1x',
		/**
		 * Changes an icon's font-size to 2em
		 */
		'2x' = 'fa-2x',
		/**
		 * Changes an icon's font-size to 3em
		 */
		'3x' = 'fa-3x',
		/**
		 * Changes an icon's font-size to 4em
		 */
		'4x' = 'fa-4x',
		/**
		 * Changes an icon's font-size to 5em
		 */
		'5x' = 'fa-5x',
		/**
		 * Changes an icon's font-size to 6em
		 */
		'6x' = 'fa-6x',
		/**
		 * Changes an icon's font-size to 7em
		 */
		'7x' = 'fa-7x',
		/**
		 * Changes an icon's font-size to 8em
		 */
		'8x' = 'fa-8x',
		/**
		 * Changes an icon's font-size to 9em
		 */
		'9x' = 'fa-9x',
		/**
		 * Changes an icon's font-size to 10em
		 */
		'10x' = 'fa-10x',
		/**
		 * Changes an icon's font-size to 0.625em (~10px) and also vertically aligns icon
		 */
		'2xs' = 'fa-2xs',
		/**
		 * Changes an icon's font-size to .75em (~12px) and also vertically aligns icon
		 */
		'xs' = 'fa-xs',
		/**
		 * Changes an icon's font-size to 0.875em (~14px) and also vertically aligns icon
		 */
		'sm' = 'fa-sm',
		/**
		 * Changes an icon's font-size to 1.25em (~20px) and also vertically aligns icon
		 */
		'lg' = 'fa-lg',
		/**
		 * Changes an icon's font-size to 1.5em (~24px) and also vertically aligns icon
		 */
		'xl' = 'fa-xl',
		/**
		 * Changes an icon's font-size to 2em (~32px) and also vertically aligns icon
		 */
		'2xl' = 'fa-2xl'
	}
	export type Name =
		| '0'
		| '1'
		| '2'
		| '3'
		| '4'
		| '5'
		| '6'
		| '7'
		| '8'
		| '9'
		| 'fill-drip'
		| 'arrows-to-circle'
		| 'circle-chevron-right'
		| 'wagon-covered'
		| 'line-height'
		| 'bagel'
		| 'transporter-7'
		| 'at'
		| 'rectangles-mixed'
		| 'phone-outgoing'
		| 'trash-can'
		| 'circle-l'
		| 'head-vr'
		| 'text-height'
		| 'user-xmark'
		| 'face-hand-yawn'
		| 'tachometer-slowest'
		| 'stethoscope'
		| 'coffin'
		| 'message'
		| 'salad'
		| 'info'
		| 'robot-astromech'
		| 'ring-diamond'
		| 'fondue-pot'
		| 'theta'
		| 'face-hand-peeking'
		| 'square-user'
		| 'down-left-and-up-right-to-center'
		| 'explosion'
		| 'file-text'
		| 'wave-square'
		| 'ring'
		| 'building-un'
		| 'dice-three'
		| 'tire-pressure-warning'
		| 'wifi-fair'
		| 'calendar-days'
		| 'mp3-player'
		| 'anchor-circle-check'
		| 'tally-4'
		| 'rectangle-history'
		| 'building-circle-arrow-right'
		| 'volleyball'
		| 'sun-haze'
		| 'text-size'
		| 'ufo'
		| 'utensil-fork'
		| 'arrows-up-to-line'
		| 'mobile-signal'
		| 'barcode-scan'
		| 'sort-down'
		| 'folder-download'
		| 'minus-circle'
		| 'face-icicles'
		| 'shovel'
		| 'door-open'
		| 'films'
		| 'sign-out-alt'
		| 'face-glasses'
		| 'nfc'
		| 'atom'
		| 'soap'
		| 'icons'
		| 'microphone-lines-slash'
		| 'closed-captioning-slash'
		| 'calculator-simple'
		| 'bridge-circle-check'
		| 'sliders-v'
		| 'map-marker-minus'
		| 'pump-medical'
		| 'fingerprint'
		| 'ski-boot'
		| 'standard-definition'
		| 'h1'
		| 'hand-point-right'
		| 'search-location'
		| 'message-bot'
		| 'step-forward'
		| 'smile-beam'
		| 'light-ceiling'
		| 'message-exclamation'
		| 'bowl-shaved-ice'
		| 'square-x'
		| 'utility-pole-double'
		| 'flag-checkered'
		| 'chevrons-up'
		| 'football'
		| 'user-vneck'
		| 'school-circle-exclamation'
		| 'crop'
		| 'angles-down'
		| 'users-rectangle'
		| 'people-roof'
		| 'square-arrow-right'
		| 'map-marker-plus'
		| 'lightbulb-exclamation-on'
		| 'people-line'
		| 'beer'
		| 'crate-empty'
		| 'diagram-predecessor'
		| 'transporter'
		| 'calendar-circle-user'
		| 'long-arrow-up'
		| 'person-carry'
		| 'fire-flame-simple'
		| 'person'
		| 'laptop'
		| 'file-csv'
		| 'menorah'
		| 'union'
		| 'chevrons-left'
		| 'heart-circle'
		| 'truck-plane'
		| 'record-vinyl'
		| 'bring-forward'
		| 'square-p'
		| 'grin-stars'
		| 'sigma'
		| 'camera-movie'
		| 'bong'
		| 'clarinet'
		| 'truck-flatbed'
		| 'spaghetti-monster-flying'
		| 'arrow-down-up-across-line'
		| 'leaf-heart'
		| 'house-building'
		| 'cheese-swiss'
		| 'utensil-spoon'
		| 'jar-wheat'
		| 'mail-bulk'
		| 'file-circle-exclamation'
		| 'bow-arrow'
		| 'cart-xmark'
		| 'xmark-hexagon'
		| 'hospital-symbol'
		| 'merge'
		| 'pager'
		| 'cart-minus'
		| 'contact-book'
		| 'pan-frying'
		| 'grid'
		| 'football-helmet'
		| 'hand-love'
		| 'trees'
		| 'strikethrough'
		| 'page'
		| 'k'
		| 'diagram-previous'
		| 'tachometer-alt-slowest'
		| 'folder-grid'
		| 'eggplant'
		| 'ram'
		| 'landmark-flag'
		| 'lips'
		| 'pencil'
		| 'backward'
		| 'caret-right'
		| 'comments'
		| 'paste'
		| 'desktop-arrow-down'
		| 'code-pull-request'
		| 'pumpkin'
		| 'clipboard-list'
		| 'pen-field'
		| 'blueberries'
		| 'truck-ramp-box'
		| 'note'
		| 'arrow-down-to-square'
		| 'user-check'
		| 'cloud-xmark'
		| 'vial-virus'
		| 'book-blank'
		| 'golf-flag-hole'
		| 'message-arrow-down'
		| 'face-unamused'
		| 'sheet-plastic'
		| 'circle-9'
		| 'blog'
		| 'user-ninja'
		| 'pencil-slash'
		| 'bowling-pins'
		| 'person-arrow-up-from-line'
		| 'down-right'
		| 'torah'
		| 'webhook'
		| 'blinds-open'
		| 'fence'
		| 'up'
		| 'quidditch'
		| 'drumstick'
		| 'square-v'
		| 'gave-dandy'
		| 'dial-off'
		| 'toggle-off'
		| 'face-smile-horns'
		| 'box-archive'
		| 'grapes'
		| 'person-drowning'
		| 'dial-max'
		| 'circle-m'
		| 'calendar-image'
		| 'circle-caret-down'
		| 'sort-numeric-down-alt'
		| 'grin-tongue-squint'
		| 'shish-kebab'
		| 'spray-can'
		| 'alarm-snooze'
		| 'scarecrow'
		| 'truck-monster'
		| 'gift-card'
		| 'w'
		| 'code-pull-request-draft'
		| 'square-b'
		| 'elephant'
		| 'globe-africa'
		| 'rainbow'
		| 'circle-notch'
		| 'tablet-screen-button'
		| 'paw'
		| 'message-question'
		| 'cloud'
		| 'trowel-bricks'
		| 'square-3'
		| 'flushed'
		| 'hospital-user'
		| 'microwave'
		| 'chf-sign'
		| 'tent-arrow-left-right'
		| 'cart-circle-arrow-up'
		| 'trash-clock'
		| 'legal'
		| 'sprinkler-ceiling'
		| 'browsers'
		| 'trillium'
		| 'music-slash'
		| 'truck-ramp'
		| 'binoculars'
		| 'microphone-slash'
		| 'box-tissue'
		| 'circle-c'
		| 'star-christmas'
		| 'chart-bullet'
		| 'motorcycle'
		| 'tree-christmas'
		| 'tire-flat'
		| 'sunglasses'
		| 'badge'
		| 'message-pen'
		| 'concierge-bell'
		| 'pencil-ruler'
		| 'arrow-progress'
		| 'chess-rook-piece'
		| 'square-root'
		| 'album-collection-circle-plus'
		| 'people-arrows'
		| 'face-angry-horns'
		| 'mars-and-venus-burst'
		| 'tombstone'
		| 'square-caret-right'
		| 'scissors'
		| 'list-music'
		| 'sun-plant-wilt'
		| 'toilets-portable'
		| 'hockey-puck'
		| 'mustache'
		| 'hyphen'
		| 'table'
		| 'user-chef'
		| 'message-image'
		| 'users-medical'
		| 'sensor-triangle-exclamation'
		| 'magnifying-glass-arrow-right'
		| 'tachograph-digital'
		| 'face-mask'
		| 'pickleball'
		| 'star-sharp-half'
		| 'users-slash'
		| 'clover'
		| 'meat'
		| 'reply'
		| 'star-and-crescent'
		| 'empty-set'
		| 'house-fire'
		| 'square-minus'
		| 'helicopter'
		| 'bird'
		| 'compass'
		| 'square-caret-down'
		| 'heart-half-stroke'
		| 'file-circle-question'
		| 'laptop-code'
		| 'joystick'
		| 'grill-fire'
		| 'rectangle-vertical-history'
		| 'swatchbook'
		| 'prescription-bottle'
		| 'navicon'
		| 'keyboard-left'
		| 'people-group'
		| 'hourglass-end'
		| 'heart-crack'
		| 'face-beam-hand-over-mouth'
		| 'humidity'
		| 'square-up-right'
		| 'kiss-beam'
		| 'corn'
		| 'roller-coaster'
		| 'photo-film-music'
		| 'radar'
		| 'sickle'
		| 'film'
		| 'coconut'
		| 'ruler-horizontal'
		| 'shield-cross'
		| 'cassette-tape'
		| 'square-terminal'
		| 'people-robbery'
		| 'lightbulb'
		| 'caret-left'
		| 'comment-middle'
		| 'trash-can-list'
		| 'block'
		| 'exclamation-circle'
		| 'school-circle-xmark'
		| 'sign-out'
		| 'face-frown-slight'
		| 'circle-chevron-down'
		| 'sidebar-flip'
		| 'unlock-keyhole'
		| 'temperature-list'
		| 'cloud-showers-heavy'
		| 'headphones-simple'
		| 'sitemap'
		| 'pipe-section'
		| 'space-station-moon-construction'
		| 'donate'
		| 'memory'
		| 'face-sleeping'
		| 'road-spikes'
		| 'fire-burner'
		| 'squirrel'
		| 'arrow-up-to-line'
		| 'flag'
		| 'face-cowboy-hat'
		| 'hanukiah'
		| 'chart-scatter-3d'
		| 'display-chart-up'
		| 'square-code'
		| 'feather'
		| 'volume-low'
		| 'xmark-to-slot'
		| 'box-taped'
		| 'comment-slash'
		| 'swords'
		| 'cloud-sun-rain'
		| 'album'
		| 'circle-n'
		| 'compress'
		| 'wheat-awn'
		| 'ankh'
		| 'hands-holding-child'
		| 'asterisk'
		| 'key-skeleton-left-right'
		| 'comment-lines'
		| 'mask-luchador'
		| 'square-check'
		| 'shredder'
		| 'book-open-cover'
		| 'sandwich'
		| 'peseta-sign'
		| 'square-parking-slash'
		| 'train-tunnel'
		| 'heading'
		| 'ghost'
		| 'face-anguished'
		| 'hockey-sticks'
		| 'abacus'
		| 'film-simple'
		| 'list'
		| 'tree-palm'
		| 'square-phone-flip'
		| 'cart-plus'
		| 'gamepad'
		| 'border-center-v'
		| 'dot-circle'
		| 'clipboard-medical'
		| 'face-dizzy'
		| 'egg'
		| 'up-to-line'
		| 'house-medical-circle-xmark'
		| 'watch-fitness'
		| 'clock-nine-thirty'
		| 'campground'
		| 'folder-plus'
		| 'jug'
		| 'soccer-ball'
		| 'snow-blowing'
		| 'paintbrush'
		| 'lock'
		| 'arrow-from-top'
		| 'gas-pump'
		| 'signal-bars-slash'
		| 'monkey'
		| 'rectangle-pro'
		| 'house-night'
		| 'hot-tub'
		| 'blanket'
		| 'map-marked'
		| 'house-flood-water'
		| 'comments-question-check'
		| 'tree'
		| 'arrows-cross'
		| 'backpack'
		| 'square-small'
		| 'folder-upload'
		| 'bridge-lock'
		| 'crosshairs-simple'
		| 'sack-dollar'
		| 'pen-to-square'
		| 'square-sliders'
		| 'car-side'
		| 'message-middle-top'
		| 'lightbulb-on'
		| 'utensil-knife'
		| 'share-nodes'
		| 'display-chart-up-circle-dollar'
		| 'wave-sine'
		| 'heart-circle-minus'
		| 'circle-w'
		| 'circle-calendar'
		| 'hourglass-half'
		| 'microscope'
		| 'sunset'
		| 'sink'
		| 'calendar-exclamation'
		| 'truck-container-empty'
		| 'hand-heart'
		| 'shopping-bag'
		| 'sort-alpha-down-alt'
		| 'mitten'
		| 'reply-time'
		| 'person-rays'
		| 'right'
		| 'circle-f'
		| 'users'
		| 'face-pleading'
		| 'eye-slash'
		| 'flask-vial'
		| 'police-box'
		| 'cucumber'
		| 'head-side-brain'
		| 'hand'
		| 'person-biking-mountain'
		| 'utensils-slash'
		| 'print-search'
		| 'folder-bookmark'
		| 'om'
		| 'pi'
		| 'flask-round-potion'
		| 'face-shush'
		| 'worm'
		| 'house-circle-xmark'
		| 'plug'
		| 'calendar-circle-exclamation'
		| 'square-i'
		| 'chevron-up'
		| 'face-saluting'
		| 'tachometer-slow'
		| 'face-persevering'
		| 'circle-camera'
		| 'hand-spock'
		| 'spider-web'
		| 'microphone-circle'
		| 'book-arrow-up'
		| 'popsicle'
		| 'command'
		| 'blinds'
		| 'stopwatch'
		| 'saxophone'
		| 'square-2'
		| 'field-hockey'
		| 'sort-shapes-up-alt'
		| 'face-scream'
		| 'square-m'
		| 'webcam'
		| 'comment-arrow-down'
		| 'lightbulb-cfl'
		| 'window-frame-open'
		| 'kiss'
		| 'bridge-circle-xmark'
		| 'period'
		| 'grin-tongue'
		| 'up-to-dotted-line'
		| 'thought-bubble'
		| 'skeleton-ribs'
		| 'raygun'
		| 'flute'
		| 'acorn'
		| 'video-arrow-up-right'
		| 'grate-droplet'
		| 'seal-exclamation'
		| 'chess-bishop'
		| 'message-sms'
		| 'coffee-beans'
		| 'hat-witch'
		| 'grin-wink'
		| 'clock-three-thirty'
		| 'hard-of-hearing'
		| 'alarm-clock'
		| 'eclipse'
		| 'face-relieved'
		| 'road-circle-check'
		| 'dice-five'
		| 'octagon-minus'
		| 'square-rss'
		| 'face-zany'
		| 'tricycle'
		| 'land-mine-on'
		| 'square-arrow-up-left'
		| 'i-cursor'
		| 'chart-mixed-up-circle-dollar'
		| 'salt-shaker'
		| 'stamp'
		| 'file-plus'
		| 'draw-square'
		| 'toilet-paper-under-slash'
		| 'stairs'
		| 'drone-front'
		| 'glass-empty'
		| 'dial-high'
		| 'user-helmet-safety'
		| 'i'
		| 'hryvnia'
		| 'arrow-down-left-and-arrow-up-right-to-center'
		| 'pills'
		| 'grin-alt'
		| 'tooth'
		| 'basketball-hoop'
		| 'objects-align-bottom'
		| 'v'
		| 'sparkles'
		| 'squid'
		| 'leafy-green'
		| 'circle-arrow-up-right'
		| 'calendars'
		| 'bangladeshi-taka-sign'
		| 'bicycle'
		| 'hammer-war'
		| 'circle-d'
		| 'spider-black-widow'
		| 'staff-snake'
		| 'pear'
		| 'head-side-cough-slash'
		| 'triangle'
		| 'apartment'
		| 'truck-medical'
		| 'pepper'
		| 'piano'
		| 'gun-squirt'
		| 'wheat-awn-circle-exclamation'
		| 'snowman'
		| 'user-alien'
		| 'shield-check'
		| 'mortar-pestle'
		| 'road-barrier'
		| 'chart-candlestick'
		| 'briefcase-blank'
		| 'school'
		| 'igloo'
		| 'parenthesis'
		| 'joint'
		| 'horse-saddle'
		| 'mug-marshmallows'
		| 'filters'
		| 'bell-on'
		| 'angle-right'
		| 'dial-med'
		| 'horse'
		| 'q'
		| 'monitor-waveform'
		| 'link-simple'
		| 'whistle'
		| 'g'
		| 'wine-glass-crack'
		| 'slot-machine'
		| 'notes-medical'
		| 'car-wash'
		| 'escalator'
		| 'comment-image'
		| 'thermometer-half'
		| 'dong-sign'
		| 'doughnut'
		| 'capsules'
		| 'poo-storm'
		| 'tally-1'
		| 'frown-open'
		| 'square-dashed'
		| 'square-j'
		| 'hand-point-up'
		| 'money-bill'
		| 'sort-size-up'
		| 'barcode-read'
		| 'baguette'
		| 'bowl-soft-serve'
		| 'face-holding-back-tears'
		| 'square-up'
		| 'train-subway-tunnel'
		| 'square-exclamation'
		| 'semicolon'
		| 'bookmark'
		| 'fan-table'
		| 'align-justify'
		| 'battery-low'
		| 'credit-card-front'
		| 'mind-share'
		| 'umbrella-beach'
		| 'helmet-un'
		| 'map-marker-smile'
		| 'arrow-to-left'
		| 'bullseye'
		| 'sushi'
		| 'message-captions'
		| 'trash-list'
		| 'bacon'
		| 'option'
		| 'hand-point-down'
		| 'arrow-up-from-bracket'
		| 'trash-plus'
		| 'objects-align-top'
		| 'folder'
		| 'face-anxious-sweat'
		| 'credit-card-blank'
		| 'file-waveform'
		| 'microchip-ai'
		| 'mug'
		| 'plane-up-slash'
		| 'radiation'
		| 'pen-circle'
		| 'bag-seedling'
		| 'chart-simple'
		| 'crutches'
		| 'parking-circle'
		| 'mars-stroke'
		| 'leaf-oak'
		| 'square-bolt'
		| 'vial'
		| 'tachometer-alt-average'
		| 'wand-magic-sparkles'
		| 'lambda'
		| 'e'
		| 'pizza'
		| 'bowl-chopsticks-noodles'
		| 'h3'
		| 'pen-clip'
		| 'bridge-circle-exclamation'
		| 'badge-percent'
		| 'user'
		| 'sensor'
		| 'comma'
		| 'school-circle-check'
		| 'toilet-paper-under'
		| 'light-emergency'
		| 'arrow-down-to-arc'
		| 'dumpster'
		| 'van-shuttle'
		| 'building-user'
		| 'light-switch'
		| 'square-caret-left'
		| 'highlighter'
		| 'wave-pulse'
		| 'key'
		| 'hat-santa'
		| 'tamale'
		| 'box-check'
		| 'bullhorn'
		| 'steak'
		| 'location-slash'
		| 'person-dolly'
		| 'globe'
		| 'synagogue'
		| 'file-chart-line'
		| 'person-half-dress'
		| 'folder-image'
		| 'calendar-pen'
		| 'road-bridge'
		| 'face-smile-tear'
		| 'message-plus'
		| 'location-arrow'
		| 'c'
		| 'tablet-button'
		| 'rectangle-history-circle-user'
		| 'building-lock'
		| 'chart-line-up'
		| 'mailbox'
		| 'truck-bolt'
		| 'pizza-slice'
		| 'money-bill-wave'
		| 'chart-area'
		| 'house-flag'
		| 'circle-three-quarters-stroke'
		| 'person-circle-minus'
		| 'scalpel'
		| 'cancel'
		| 'bell-exclamation'
		| 'circle-bookmark'
		| 'egg-fried'
		| 'face-weary'
		| 'uniform-martial-arts'
		| 'camera-rotate'
		| 'sun-dust'
		| 'comment-text'
		| 'spray-can-sparkles'
		| 'signal-bars'
		| 'diamond-exclamation'
		| 'star'
		| 'dial-min'
		| 'repeat'
		| 'cross'
		| 'page-caret-down'
		| 'box'
		| 'venus-mars'
		| 'clock-seven-thirty'
		| 'mouse-pointer'
		| 'clock-four-thirty'
		| 'signal-bars-good'
		| 'cactus'
		| 'lightbulb-gear'
		| 'maximize'
		| 'charging-station'
		| 'triangle-circle-square'
		| 'plane-tail'
		| 'tachometer-fastest'
		| 'circle-u'
		| 'shield-slash'
		| 'square-phone-hangup'
		| 'arrow-up-left'
		| 'transporter-1'
		| 'peanuts'
		| 'shuffle'
		| 'running'
		| 'mobile-retro'
		| 'grip-lines-vertical'
		| 'bin-bottles-recycle'
		| 'arrow-up-from-square'
		| 'page-break'
		| 'bracket-curly-right'
		| 'spider'
		| 'clock-three'
		| 'hands-bound'
		| 'scalpel-path'
		| 'file-invoice-dollar'
		| 'pipe-smoking'
		| 'face-astonished'
		| 'window'
		| 'plane-circle-exclamation'
		| 'ear'
		| 'file-lock'
		| 'diagram-venn'
		| 'x-ray'
		| 'goal-net'
		| 'coffin-cross'
		| 'spell-check'
		| 'map-marker-xmark'
		| 'circle-quarter-stroke'
		| 'lasso'
		| 'slash'
		| 'portal-enter'
		| 'calendar-star'
		| 'mouse'
		| 'sign-in'
		| 'pegasus'
		| 'files-medical'
		| 'nfc-lock'
		| 'ski-lift'
		| 'square-6'
		| 'store-alt-slash'
		| 'wind-turbine'
		| 'sliders-simple'
		| 'grid-round'
		| 'badge-sheriff'
		| 'server'
		| 'virus-covid-slash'
		| 'intersection'
		| 'shop-lock'
		| 'family'
		| 'hourglass-start'
		| 'user-hair-buns'
		| 'blender-phone'
		| 'hourglass-clock'
		| 'person-seat-reclined'
		| 'send'
		| 'message-arrow-up'
		| 'lightbulb-exclamation'
		| 'layer-minus'
		| 'chart-pie-simple-circle-currency'
		| 'circle-e'
		| 'building-wheat'
		| 'tachometer-alt-fastest'
		| 'person-breastfeeding'
		| 'apostrophe'
		| 'fire-hydrant'
		| 'sign-in-alt'
		| 'video-plus'
		| 'square-right'
		| 'comment-smile'
		| 'venus'
		| 'passport'
		| 'inbox-in'
		| 'heartbeat'
		| 'circle-8'
		| 'clouds-moon'
		| 'clock-ten-thirty'
		| 'people-carry'
		| 'folder-user'
		| 'trash-can-xmark'
		| 'temperature-high'
		| 'microchip'
		| 'left-long-to-line'
		| 'crown'
		| 'weight-hanging'
		| 'xmarks-lines'
		| 'file-prescription'
		| 'calendar-range'
		| 'flower-daffodil'
		| 'hand-back-point-up'
		| 'weight'
		| 'star-exclamation'
		| 'books'
		| 'user-group'
		| 'sort-alpha-up'
		| 'layer-plus'
		| 'play-pause'
		| 'block-question'
		| 'zzz'
		| 'scanner-image'
		| 'tv-retro'
		| 'square-t'
		| 'farm'
		| 'chess-knight'
		| 'bars-sort'
		| 'pallet-boxes'
		| 'laugh-squint'
		| 'code-simple'
		| 'bolt-slash'
		| 'panel-fire'
		| 'binary-circle-check'
		| 'comment-minus'
		| 'burrito'
		| 'violin'
		| 'objects-column'
		| 'square-chevron-down'
		| 'comment-plus'
		| 'triangle-music'
		| 'wheelchair'
		| 'user-pilot-tie'
		| 'piano-keyboard'
		| 'bed-empty'
		| 'circle-arrow-up'
		| 'toggle-on'
		| 'rectangle-vertical'
		| 'walking'
		| 'l'
		| 'signal-stream'
		| 'down-to-bracket'
		| 'circle-z'
		| 'stars'
		| 'fire'
		| 'procedures'
		| 'house-day'
		| 'space-shuttle'
		| 'shirt-long-sleeve'
		| 'chart-pie-simple'
		| 'laugh'
		| 'folder-open'
		| 'album-collection-circle-user'
		| 'candy'
		| 'soup'
		| 'flatbread'
		| 'heart-circle-plus'
		| 'code-fork'
		| 'city'
		| 'signal-bars-weak'
		| 'microphone-lines'
		| 'clock-twelve'
		| 'pepper-hot'
		| 'citrus-slice'
		| 'sheep'
		| 'unlock'
		| 'colon-sign'
		| 'headset'
		| 'badger-honey'
		| 'h4'
		| 'store-slash'
		| 'road-circle-xmark'
		| 'signal-slash'
		| 'user-minus'
		| 'mars-stroke-v'
		| 'glass-cheers'
		| 'taco'
		| 'plus-hexagon'
		| 'clipboard'
		| 'house-circle-exclamation'
		| 'file-upload'
		| 'wifi'
		| 'messages'
		| 'bathtub'
		| 'umbrella-simple'
		| 'rectangle-history-circle-plus'
		| 'underline'
		| 'prescription-bottle-pill'
		| 'user-pen'
		| 'binary-slash'
		| 'square-o'
		| 'signature'
		| 'stroopwafel'
		| 'bold'
		| 'anchor-lock'
		| 'building-ngo'
		| 'transporter-3'
		| 'engine-warning'
		| 'circle-down-right'
		| 'square-k'
		| 'manat-sign'
		| 'money-check-pen'
		| 'not-equal'
		| 'border-top-left'
		| 'map-marked-alt'
		| 'tilde'
		| 'jedi'
		| 'square-poll-vertical'
		| 'sort-shapes-down-alt'
		| 'mug-hot'
		| 'dog-leashed'
		| 'car-battery'
		| 'face-downcast-sweat'
		| 'mailbox-flag-up'
		| 'memo-circle-info'
		| 'gift'
		| 'dice-two'
		| 'volume'
		| 'transporter-5'
		| 'gauge-circle-bolt'
		| 'coin-front'
		| 'file-slash'
		| 'message-arrow-up-right'
		| 'treasure-chest'
		| 'chess-queen'
		| 'paintbrush-fine'
		| 'glasses'
		| 'hood-cloak'
		| 'square-quote'
		| 'up-left'
		| 'bring-front'
		| 'chess-board'
		| 'cheeseburger'
		| 'building-circle-check'
		| 'repeat-1'
		| 'arrow-to-bottom'
		| 'grid-5'
		| 'right-long-to-line'
		| 'person-chalkboard'
		| 'mars-stroke-right'
		| 'hand-rock'
		| 'grid-round-5'
		| 'tally'
		| 'square-caret-up'
		| 'cloud-showers-water'
		| 'chart-bar'
		| 'hands-wash'
		| 'less-than-equal'
		| 'train'
		| 'up-from-dotted-line'
		| 'low-vision'
		| 'traffic-light-go'
		| 'face-exhaling'
		| 'sensor-fire'
		| 'user-unlock'
		| 'hexagon-divide'
		| '00'
		| 'crow'
		| 'cassette-betamax'
		| 'sailboat'
		| 'window-restore'
		| 'nfc-magnifying-glass'
		| 'file-binary'
		| 'circle-v'
		| 'square-plus'
		| 'bowl-scoops'
		| 'mistletoe'
		| 'custard'
		| 'lacrosse-stick'
		| 'hockey-mask'
		| 'sunrise'
		| 'panel-ews'
		| 'torii-gate'
		| 'cloud-exclamation'
		| 'message-lines'
		| 'frog'
		| 'bucket'
		| 'floppy-disk-pen'
		| 'image'
		| 'window-frame'
		| 'microphone'
		| 'cow'
		| 'file-zip'
		| 'square-ring'
		| 'down-from-line'
		| 'caret-up'
		| 'shield-xmark'
		| 'screwdriver'
		| 'sort-circle-down'
		| 'folder-closed'
		| 'house-tsunami'
		| 'square-nfi'
		| 'forklift'
		| 'arrow-up-from-ground-water'
		| 'bracket-square-right'
		| 'martini-glass'
		| 'undo-alt'
		| 'table-columns'
		| 'square-a'
		| 'tick'
		| 'lemon'
		| 'head-side-mask'
		| 'handshake'
		| 'gem'
		| 'dolly'
		| 'smoking'
		| 'minimize'
		| 'refrigerator'
		| 'monument'
		| 'xmark-octagon'
		| 'align-slash'
		| 'snowplow'
		| 'angles-right'
		| 'truck-ramp-couch'
		| 'cannabis'
		| 'play-circle'
		| 'arrow-up-right-and-arrow-down-left-from-center'
		| 'tablets'
		| '360-degrees'
		| 'ethernet'
		| 'euro'
		| 'chair'
		| 'circle-check'
		| 'square-dashed-circle-plus'
		| 'money-simple-from-bracket'
		| 'bat'
		| 'stop-circle'
		| 'head-side-headphones'
		| 'phone-rotary'
		| 'drafting-compass'
		| 'plate-wheat'
		| 'calendar-circle-minus'
		| 'chopsticks'
		| 'car-wrench'
		| 'icicles'
		| 'person-shelter'
		| 'neuter'
		| 'id-badge'
		| 'kazoo'
		| 'marker'
		| 'bin-bottles'
		| 'laugh-beam'
		| 'square-arrow-down-left'
		| 'battery-bolt'
		| 'tree-large'
		| 'helicopter-symbol'
		| 'aperture'
		| 'universal-access'
		| 'gear-complex'
		| 'file-search'
		| 'up-right'
		| 'circle-chevron-up'
		| 'user-police'
		| 'lari-sign'
		| 'volcano'
		| 'teddy-bear'
		| 'stocking'
		| 'person-walking-dashed-line-arrow-right'
		| 'image-slash'
		| 'mask-snorkel'
		| 'smoke'
		| 'sterling-sign'
		| 'battery-exclamation'
		| 'viruses'
		| 'square-person-confined'
		| 'user-tie'
		| 'long-arrow-down'
		| 'tent-arrow-down-to-line'
		| 'certificate'
		| 'crystal-ball'
		| 'reply-all'
		| 'suitcase'
		| 'skating'
		| 'star-shooting'
		| 'binary-lock'
		| 'funnel-dollar'
		| 'camera-retro'
		| 'circle-arrow-down'
		| 'comment-pen'
		| 'file-import'
		| 'banjo'
		| 'square-arrow-up-right'
		| 'light-emergency-on'
		| 'kerning'
		| 'box-open'
		| 'square-f'
		| 'scroll'
		| 'spa'
		| 'arrow-left-from-line'
		| 'strawberry'
		| 'location-pin-lock'
		| 'pause'
		| 'clock-eight-thirty'
		| 'plane-engines'
		| 'hill-avalanche'
		| 'thermometer-empty'
		| 'bomb'
		| 'tachometer-alt-slow'
		| 'registered'
		| 'trash-can-plus'
		| 'vcard'
		| 'scale-unbalanced-flip'
		| 'globe-snow'
		| 'subscript'
		| 'directions'
		| 'integral'
		| 'burst'
		| 'laptop-house'
		| 'tired'
		| 'money-bills'
		| 'blinds-raised'
		| 'smog'
		| 'ufo-beam'
		| 'circle-caret-up'
		| 'user-vneck-hair-long'
		| 'square-a-lock'
		| 'crutch'
		| 'gas-pump-slash'
		| 'cloud-upload'
		| 'palette'
		| 'transporter-4'
		| 'chart-mixed-up-circle-currency'
		| 'objects-align-right'
		| 'arrows-turn-right'
		| 'vest'
		| 'pig'
		| 'inbox-full'
		| 'envelope-circle'
		| 'triangle-person-digging'
		| 'ferry'
		| 'bullseye-arrow'
		| 'arrows-down-to-people'
		| 'sprout'
		| 'clock-seven'
		| 'left-right'
		| 'boxes-packing'
		| 'circle-arrow-left'
		| 'flashlight'
		| 'group-arrows-rotate'
		| 'bowl-food'
		| 'square-9'
		| 'candy-cane'
		| 'sort-amount-down'
		| 'usd-square'
		| 'phone-arrow-right'
		| 'hand-holding-seedling'
		| 'message-check'
		| 'thunderstorm'
		| 'chart-line-up-down'
		| 'text-slash'
		| 'watch'
		| 'circle-down-left'
		| 'text'
		| 'projector'
		| 'smile-wink'
		| 'tombstone-blank'
		| 'chess-king-piece'
		| 'circle-6'
		| 'left'
		| 'file-word'
		| 'file-powerpoint'
		| 'square-down'
		| 'objects-align-center-vertical'
		| 'arrows-left-right'
		| 'house-lock'
		| 'cloud-download'
		| 'wreath'
		| 'children'
		| 'meter-droplet'
		| 'chalkboard'
		| 'user-large-slash'
		| 'signal-strong'
		| 'lollypop'
		| 'list-tree'
		| 'envelope-open'
		| 'draw-circle'
		| 'cat-space'
		| 'handshake-simple-slash'
		| 'rabbit-running'
		| 'memo-pad'
		| 'mattress-pillow'
		| 'alarm-plus'
		| 'alicorn'
		| 'comment-question'
		| 'gingerbread-man'
		| 'guarani-sign'
		| 'burger-fries'
		| 'mug-tea'
		| 'border-top'
		| 'sync'
		| 'circle-book-open'
		| 'arrows-to-dotted-line'
		| 'fire-extinguisher'
		| 'garage-open'
		| 'shelves-empty'
		| 'cruzeiro-sign'
		| 'watch-apple'
		| 'watch-calculator'
		| 'list-dropdown'
		| 'cabinet-filing'
		| 'burger-soda'
		| 'square-arrow-up'
		| 'greater-than-equal'
		| 'pallet-box'
		| 'face-confounded'
		| 'shield-halved'
		| 'truck-plow'
		| 'book-atlas'
		| 'virus'
		| 'grid-round-2'
		| 'comment-middle-top'
		| 'envelope-circle-check'
		| 'layer-group'
		| 'restroom-simple'
		| 'arrows-to-dot'
		| 'border-outer'
		| 'hashtag-lock'
		| 'clock-two-thirty'
		| 'archway'
		| 'heart-circle-check'
		| 'house-damage'
		| 'file-zipper'
		| 'heart-half'
		| 'comment-check'
		| 'square'
		| 'memo'
		| 'martini-glass-empty'
		| 'couch'
		| 'cedi-sign'
		| 'italic'
		| 'glass-citrus'
		| 'calendar-lines-pen'
		| 'church'
		| 'snowmobile'
		| 'face-hushed'
		| 'comments-dollar'
		| 'pickaxe'
		| 'link-simple-slash'
		| 'democrat'
		| 'face-confused'
		| 'pinball'
		| 'z'
		| 'skiing'
		| 'deer'
		| 'input-pipe'
		| 'road-lock'
		| 'a'
		| 'bookmark-slash'
		| 'temperature-down'
		| 'mace'
		| 'feather-pointed'
		| 'sausage'
		| 'trash-can-clock'
		| 'p'
		| 'broom-wide'
		| 'snowflake'
		| 'stomach'
		| 'newspaper'
		| 'rectangle-ad'
		| 'guitar-electric'
		| 'arrow-turn-down-right'
		| 'moon-cloud'
		| 'bread-slice-butter'
		| 'circle-arrow-right'
		| 'users-crown'
		| 'circle-i'
		| 'toilet-paper-check'
		| 'filter-circle-xmark'
		| 'locust'
		| 'unsorted'
		| 'list-ol'
		| 'chart-waterfall'
		| 'sparkle'
		| 'face-party'
		| 'kidneys'
		| 'wifi-exclamation'
		| 'chart-network'
		| 'person-dress-burst'
		| 'dice-d4'
		| 'money-check-dollar'
		| 'vector-square'
		| 'bread-slice'
		| 'language'
		| 'wheat-awn-slash'
		| 'kiss-wink-heart'
		| 'dagger'
		| 'podium'
		| 'memo-circle-check'
		| 'route-highway'
		| 'down-to-line'
		| 'filter'
		| 'square-g'
		| 'phone-circle'
		| 'clipboard-prescription'
		| 'user-nurse-hair'
		| 'question'
		| 'file-signature'
		| 'toggle-large-on'
		| 'up-down-left-right'
		| 'dryer-heat'
		| 'house-chimney-user'
		| 'hand-holding-heart'
		| 'sort-size-up-alt'
		| 'train-track'
		| 'puzzle-piece'
		| 'money-check'
		| 'star-half-stroke'
		| 'file-exclamation'
		| 'code'
		| 'whiskey-glass'
		| 'moon-stars'
		| 'building-circle-exclamation'
		| 'clothes-hanger'
		| 'mobile-notch'
		| 'magnifying-glass-chart'
		| 'external-link'
		| 'cubes-stacked'
		| 'images-user'
		| 'won'
		| 'image-polaroid-user'
		| 'virus-covid'
		| 'square-ellipsis'
		| 'pie'
		| 'chess-knight-piece'
		| 'austral-sign'
		| 'cloud-plus'
		| 'f'
		| 'leaf'
		| 'bed-bunk'
		| 'road'
		| 'taxi'
		| 'person-circle-plus'
		| 'pie-chart'
		| 'bolt-lightning'
		| 'clock-eight'
		| 'sack-xmark'
		| 'file-excel'
		| 'file-contract'
		| 'fish-fins'
		| 'circle-q'
		| 'building-flag'
		| 'grin-beam'
		| 'object-ungroup'
		| 'face-disguise'
		| 'circle-arrow-down-right'
		| 'alien-monster'
		| 'hand-point-ribbon'
		| 'poop'
		| 'object-exclude'
		| 'telescope'
		| 'map-marker'
		| 'square-list'
		| 'kaaba'
		| 'toilet-paper'
		| 'helmet-safety'
		| 'comment-code'
		| 'sim-cards'
		| 'starship'
		| 'eject'
		| 'circle-right'
		| 'plane-circle-check'
		| 'seal'
		| 'user-cowboy'
		| 'hexagon-vertical-nft'
		| 'meh-rolling-eyes'
		| 'bread-loaf'
		| 'rings-wedding'
		| 'object-group'
		| 'french-fries'
		| 'line-chart'
		| 'calendar-download'
		| 'send-back'
		| 'mask-ventilator'
		| 'signature-lock'
		| 'arrow-right'
		| 'signs-post'
		| 'plus-octagon'
		| 'cash-register'
		| 'person-circle-question'
		| 'melon-slice'
		| 'space-station-moon'
		| 'message-smile'
		| 'cup-straw'
		| 'left-from-line'
		| 'h'
		| 'shopping-basket-alt'
		| 'hands-holding-heart'
		| 'clock-nine'
		| 'tarp'
		| 'face-sleepy'
		| 'hand-horns'
		| 'tools'
		| 'arrows-to-eye'
		| 'circle-three-quarters'
		| 'trophy-star'
		| 'plug-circle-bolt'
		| 'face-thermometer'
		| 'grid-round-4'
		| 'shirt-running'
		| 'book-circle-arrow-up'
		| 'face-nauseated'
		| 'heart'
		| 'file-chart-pie'
		| 'mars-and-venus'
		| 'house-user'
		| 'circle-arrow-down-left'
		| 'dumpster-fire'
		| 'minus-hexagon'
		| 'left-to-line'
		| 'house-crack'
		| 'paw-simple'
		| 'arrow-left-long-to-line'
		| 'parentheses'
		| 'martini-glass-citrus'
		| 'user-shakespeare'
		| 'arrow-right-to-arc'
		| 'surprise'
		| 'bottle-water'
		| 'pause-circle'
		| 'gauge-circle-plus'
		| 'folders'
		| 'angel'
		| 'value-absolute'
		| 'rabbit'
		| 'toilet-paper-slash'
		| 'circle-euro'
		| 'apple-whole'
		| 'kitchen-set'
		| 'diamond-half'
		| 'lock-keyhole'
		| 'r'
		| 'thermometer-quarter'
		| 'square-info'
		| 'wifi-slash'
		| 'toilet-paper-xmark'
		| 'hands-usd'
		| 'cube'
		| 'sort-shapes-down'
		| 'bitcoin-sign'
		| 'shutters'
		| 'shield-dog'
		| 'solar-panel'
		| 'lock-open'
		| 'table-tree'
		| 'house-chimney-heart'
		| 'tally-3'
		| 'elevator'
		| 'money-bill-transfer'
		| 'money-bill-trend-up'
		| 'house-flood-water-circle-arrow-right'
		| 'square-poll-horizontal'
		| 'circle'
		| 'cart-circle-exclamation'
		| 'sword'
		| 'fast-backward'
		| 'recycle'
		| 'user-astronaut'
		| 'interrobang'
		| 'plane-slash'
		| 'circle-dashed'
		| 'trademark'
		| 'basketball'
		| 'utensils-alt'
		| 'satellite-dish'
		| 'badge-check'
		| 'circle-up'
		| 'slider'
		| 'mobile-screen-button'
		| 'clock-one-thirty'
		| 'inbox-out'
		| 'cloud-slash'
		| 'volume-up'
		| 'users-rays'
		| 'wallet'
		| 'octagon-check'
		| 'flatbread-stuffed'
		| 'clipboard-check'
		| 'cart-circle-plus'
		| 'truck-clock'
		| 'pool-8-ball'
		| 'file-audio'
		| 'turn-down-left'
		| 'lock-hashtag'
		| 'chart-radar'
		| 'staff'
		| 'hamburger'
		| 'utility-pole'
		| 'transporter-6'
		| 'wrench'
		| 'bugs'
		| 'vector-polygon'
		| 'diagram-nested'
		| 'rupee'
		| 'file-image'
		| 'question-circle'
		| 'image-user'
		| 'buoy'
		| 'plane-departure'
		| 'handshake-slash'
		| 'book-bookmark'
		| 'border-center-h'
		| 'can-food'
		| 'typewriter'
		| 'arrow-right-from-arc'
		| 'circle-k'
		| 'face-hand-over-mouth'
		| 'popcorn'
		| 'house-water'
		| 'object-subtract'
		| 'code-branch'
		| 'warehouse-full'
		| 'hat-cowboy'
		| 'bridge'
		| 'phone-flip'
		| 'arrow-down-from-dotted-line'
		| 'file-doc'
		| 'square-quarters'
		| 'truck-front'
		| 'cat'
		| 'trash-xmark'
		| 'circle-caret-left'
		| 'files'
		| 'anchor-circle-exclamation'
		| 'face-clouds'
		| 'user-crown'
		| 'truck-field'
		| 'route'
		| 'cart-circle-check'
		| 'clipboard-question'
		| 'panorama'
		| 'comment-medical'
		| 'teeth-open'
		| 'user-tie-hair-long'
		| 'file-circle-minus'
		| 'head-side-medical'
		| 'tags'
		| 'wine-glass'
		| 'forward-fast'
		| 'meh-blank'
		| 'user-robot'
		| 'square-parking'
		| 'card-diamond'
		| 'face-zipper'
		| 'face-raised-eyebrow'
		| 'house-signal'
		| 'square-chevron-up'
		| 'tasks-alt'
		| 'faucet-drip'
		| 'arrows-to-line'
		| 'dolphin'
		| 'arrow-up-right'
		| 'circle-r'
		| 'dolly-flatbed'
		| 'smoking-ban'
		| 'sort-circle-up'
		| 'terminal'
		| 'mobile-button'
		| 'house-medical-flag'
		| 'shopping-basket'
		| 'tape'
		| 'chestnut'
		| 'bus-simple'
		| 'eye'
		| 'sad-cry'
		| 'heat'
		| 'ticket-airline'
		| 'boot-heeled'
		| 'compress-arrows'
		| 'audio-description'
		| 'person-military-to-person'
		| 'file-shield'
		| 'hexagon'
		| 'manhole'
		| 'user-slash'
		| 'pen'
		| 'tower-observation'
		| 'floppy-disks'
		| 'toilet-paper-reverse-alt'
		| 'file-code'
		| 'signal'
		| 'pump'
		| 'bus'
		| 'heart-circle-xmark'
		| 'arrow-up-left-from-circle'
		| 'house-chimney'
		| 'window-maximize'
		| 'dryer'
		| 'frown'
		| 'chess-bishop-piece'
		| 'shirt-tank-top'
		| 'scroll-ribbon'
		| 'screencast'
		| 'walker'
		| 'prescription'
		| 'store-alt'
		| 'save'
		| 'vihara'
		| 'face-kiss-closed-eyes'
		| 'scale-unbalanced'
		| 'file-user'
		| 'user-police-tie'
		| 'face-tongue-money'
		| 'tennis-ball'
		| 'square-l'
		| 'sort-up'
		| 'calendar-upload'
		| 'commenting'
		| 'plant-wilt'
		| 'scarf'
		| 'album-circle-plus'
		| 'user-nurse-hair-long'
		| 'diamond'
		| 'square-left'
		| 'grin-squint'
		| 'circle-ellipsis-vertical'
		| 'hand-holding-usd'
		| 'grid-dividers'
		| 'bacterium'
		| 'hand-pointer'
		| 'drum-steelpan'
		| 'hand-scissors'
		| 'praying-hands'
		| 'face-pensive'
		| 'user-music'
		| 'redo'
		| 'messages-dollar'
		| 'sensor-on'
		| 'balloon'
		| 'biohazard'
		| 'chess-queen-piece'
		| 'location'
		| 'mars-double'
		| 'house-person-leave'
		| 'ruler-triangle'
		| 'card-club'
		| 'child-dress'
		| 'users-between-lines'
		| 'lungs-virus'
		| 'spinner-third'
		| 'grin-tears'
		| 'phone'
		| 'mouse-alt'
		| 'calendar-xmark'
		| 'child-reaching'
		| 'table-layout'
		| 'narwhal'
		| 'ramp-loading'
		| 'calendar-circle-plus'
		| 'toothbrush'
		| 'border-inner'
		| 'paw-claws'
		| 'kiwi-fruit'
		| 'traffic-light-slow'
		| 'rectangle-code'
		| 'head-side-virus'
		| 'keyboard-brightness'
		| 'books-medical'
		| 'lightbulb-slash'
		| 'house-blank'
		| 'square-5'
		| 'square-heart'
		| 'puzzle'
		| 'user-gear'
		| 'pipe-circle-check'
		| 'sort-numeric-up'
		| 'octagon-exclamation'
		| 'dial-low'
		| 'door-closed'
		| 'phone-laptop'
		| 'conveyor-belt-boxes'
		| 'shield-virus'
		| 'starfighter-twin-ion-engine-advanced'
		| 'dice-six'
		| 'starfighter-twin-ion-engine'
		| 'rocket-launch'
		| 'mosquito-net'
		| 'vent-damper'
		| 'bridge-water'
		| 'debug'
		| 'person-booth'
		| 'text-width'
		| 'garage-car'
		| 'square-kanban'
		| 'hat-wizard'
		| 'pen-fancy'
		| 'coffee-pot'
		| 'mouse-field'
		| 'person-digging'
		| 'shower-down'
		| 'box-circle-check'
		| 'brightness'
		| 'car-side-bolt'
		| 'ornament'
		| 'phone-incoming'
		| 'cloud-word'
		| 'hand-fingers-crossed'
		| 'trash'
		| 'tachometer-average'
		| 'sort-size-down-alt'
		| 'book-medical'
		| 'face-melting'
		| 'poo'
		| 'pen-clip-slash'
		| 'quote-right'
		| 'scroll-old'
		| 'guitars'
		| 'phone-xmark'
		| 'hose'
		| 'clock-six'
		| 'tshirt'
		| 'billboard'
		| 'square-r'
		| 'cubes'
		| 'envelope-open-dollar'
		| 'divide'
		| 'sun-cloud'
		| 'lamp-floor'
		| 'square-7'
		| 'tenge'
		| 'headphones'
		| 'hands-holding'
		| 'campfire'
		| 'circle-ampersand'
		| 'snowflakes'
		| 'hands-clapping'
		| 'republican'
		| 'leaf-maple'
		| 'arrow-left'
		| 'person-circle-xmark'
		| 'ruler'
		| 'cup-straw-swoosh'
		| 'temperature-sun'
		| 'align-left'
		| 'dice-d6'
		| 'restroom'
		| 'rectangle-hd'
		| 'j'
		| 'galaxy'
		| 'users-viewfinder'
		| 'file-video'
		| 'cherries'
		| 'up-right-from-square'
		| 'sort-circle'
		| 'th'
		| 'file-pdf'
		| 'siren'
		| 'arrow-up-to-dotted-line'
		| 'landscape'
		| 'tank-water'
		| 'curling'
		| 'gamepad-modern'
		| 'messages-question'
		| 'book-bible'
		| 'o'
		| 'suitcase-medical'
		| 'briefcase-arrow-right'
		| 'expand-wide'
		| 'clock-eleven-thirty'
		| 'rv'
		| 'user-secret'
		| 'otter'
		| 'dreidel'
		| 'person-dress'
		| 'comment-dollar'
		| 'business-time'
		| 'flower-tulip'
		| 'people-pants-simple'
		| 'cloud-drizzle'
		| 'th-large'
		| 'tanakh'
		| 'solar-system'
		| 'seal-question'
		| 'volume-control-phone'
		| 'disc-drive'
		| 'hat-cowboy-side'
		| 'table-rows'
		| 'map-marker-exclamation'
		| 'face-fearful'
		| 'clipboard-user'
		| 'bus-school'
		| 'film-slash'
		| 'square-arrow-down-right'
		| 'book-spells'
		| 'washing-machine'
		| 'child'
		| 'lira-sign'
		| 'user-visor'
		| 'file-plus-minus'
		| 'chess-clock-flip'
		| 'satellite'
		| 'plane-lock'
		| 'steering-wheel'
		| 'tag'
		| 'stretcher'
		| 'book-section'
		| 'inboxes'
		| 'coffee-bean'
		| 'circle-yen'
		| 'brackets-curly'
		| 'ellipsis-v-alt'
		| 'comment'
		| 'square-1'
		| 'cake'
		| 'head-side'
		| 'envelope'
		| 'dolly-empty'
		| 'face-tissue'
		| 'angles-up'
		| 'bin-recycle'
		| 'paperclip'
		| 'chart-line-down'
		| 'arrow-right-to-city'
		| 'lock-a'
		| 'ribbon'
		| 'lungs'
		| 'person-pinball'
		| 'sort-numeric-up-alt'
		| 'apple-core'
		| 'circle-y'
		| 'h6'
		| 'litecoin-sign'
		| 'circle-small'
		| 'border-none'
		| 'arrow-turn-down-left'
		| 'circle-nodes'
		| 'parachute-box'
		| 'message-medical'
		| 'rugby-ball'
		| 'comment-music'
		| 'indent'
		| 'tree-deciduous'
		| 'puzzle-piece-simple'
		| 'truck-field-un'
		| 'nfc-trash'
		| 'hourglass'
		| 'mountain'
		| 'file-xmark'
		| 'house-heart'
		| 'house-chimney-blank'
		| 'meter-bolt'
		| 'user-md'
		| 'slash-back'
		| 'info-circle'
		| 'fishing-rod'
		| 'hammer-crash'
		| 'message-heart'
		| 'cloud-meatball'
		| 'camera-polaroid'
		| 'camera'
		| 'square-virus'
		| 'cart-arrow-up'
		| 'meteor'
		| 'car-on'
		| 'sleigh'
		| 'sort-numeric-down'
		| 'buoy-mooring'
		| 'square-4'
		| 'hand-holding-water'
		| 'tricycle-adult'
		| 'waveform'
		| 'water'
		| 'star-sharp-half-stroke'
		| 'nfc-signal'
		| 'plane-prop'
		| 'calendar-check'
		| 'clock-desk'
		| 'calendar-time'
		| 'braille'
		| 'prescription-bottle-medical'
		| 'plate-utensils'
		| 'family-pants'
		| 'hose-reel'
		| 'house-window'
		| 'landmark'
		| 'truck'
		| 'crosshairs'
		| 'cloud-rainbow'
		| 'person-cane'
		| 'alien'
		| 'tent'
		| 'laptop-binary'
		| 'vest-patches'
		| 'people-dress-simple'
		| 'check-double'
		| 'sort-alpha-down'
		| 'bowling-ball-pin'
		| 'bell-school-slash'
		| 'plus-large'
		| 'money-bill-wheat'
		| 'screenshot'
		| 'message-music'
		| 'car-building'
		| 'border-style-alt'
		| 'octagon'
		| 'comment-arrow-up-right'
		| 'octagon-divide'
		| 'cookie'
		| 'undo'
		| 'tv-music'
		| 'hdd'
		| 'reel'
		| 'grin-squint-tears'
		| 'dumbbell'
		| 'rectangle-list'
		| 'tarp-droplet'
		| 'alarm-exclamation'
		| 'house-medical-circle-check'
		| 'traffic-cone'
		| 'grate'
		| 'arrow-down-right'
		| 'skiing-nordic'
		| 'calendar-plus'
		| 'portal-exit'
		| 'plane-arrival'
		| 'cowbell-more'
		| 'circle-left'
		| 'distribute-spacing-vertical'
		| 'signal-bars-fair'
		| 'sportsball'
		| 'game-console-handheld-crank'
		| 'train-subway'
		| 'chart-gantt'
		| 'face-smile-upside-down'
		| 'ball-pile'
		| 'badge-dollar'
		| 'money-bills-simple'
		| 'list-timeline'
		| 'inr'
		| 'crop-simple'
		| 'money-bill-alt'
		| 'long-arrow-alt-left'
		| 'keyboard-down'
		| 'circle-up-right'
		| 'thunderstorm-moon'
		| 'dna'
		| 'virus-slash'
		| 'bracket-round-right'
		| 'circle-sterling'
		| 'circle-5'
		| 'subtract'
		| 'flame'
		| 'right-to-line'
		| 'gif'
		| 'chess'
		| 'trash-slash'
		| 'long-arrow-left'
		| 'plug-circle-check'
		| 'font-case'
		| 'street-view'
		| 'arrow-down-left'
		| 'franc-sign'
		| 'flask-round-poison'
		| 'volume-off'
		| 'book-circle-arrow-right'
		| 'user-chart'
		| 'hands-asl-interpreting'
		| 'presentation'
		| 'circle-bolt'
		| 'face-smile-halo'
		| 'cart-circle-arrow-down'
		| 'house-return'
		| 'message-xmark'
		| 'file-certificate'
		| 'user-doctor-hair-long'
		| 'camera-security'
		| 'gear'
		| 'tint-slash'
		| 'book-heart'
		| 'mosque'
		| 'duck'
		| 'mosquito'
		| 'star-of-david'
		| 'flag-swallowtail'
		| 'person-military-rifle'
		| 'car-garage'
		| 'shopping-cart'
		| 'book-font'
		| 'shield-plus'
		| 'vials'
		| 'eye-dropper-full'
		| 'distribute-spacing-horizontal'
		| 'tablet-rugged'
		| 'temperature-snow'
		| 'moped'
		| 'smile-plus'
		| 'radio-tuner'
		| 'face-swear'
		| 'water-lower'
		| 'scanner-touchscreen'
		| 'circle-7'
		| 'plug-circle-plus'
		| 'ski-jump'
		| 'place-of-worship'
		| 'water-rise'
		| 'waveform-path'
		| 'split'
		| 'film-cannister'
		| 'folder-xmark'
		| 'toilet-paper-blank'
		| 'tablet-screen'
		| 'hexagon-vertical-nft-slanted'
		| 'folder-music'
		| 'display-medical'
		| 'share-all'
		| 'peapod'
		| 'chess-clock'
		| 'axe'
		| 'square-d'
		| 'grip-vertical'
		| 'mobile-signal-out'
		| 'level-up'
		| 'u'
		| 'arrow-up-from-dotted-line'
		| 'square-root-variable'
		| 'light-switch-on'
		| 'sort-alt'
		| 'raindrops'
		| 'minus-large'
		| 'clock'
		| 'input-numeric'
		| 'truck-tow'
		| 'step-backward'
		| 'pallet'
		| 'car-bolt'
		| 'expand-arrows'
		| 'faucet'
		| 'cloud-sleet'
		| 'lamp-street'
		| 'list-radio'
		| 'pen-nib-slash'
		| 'baseball-bat-ball'
		| 'square-up-left'
		| 'overline'
		| 's'
		| 'timeline'
		| 'keyboard'
		| 'arrows-from-dotted-line'
		| 'usb-drive'
		| 'ballot'
		| 'caret-down'
		| 'map-marker-alt-slash'
		| 'cards'
		| 'house-chimney-medical'
		| 'glove-boxing'
		| 'thermometer-three-quarters'
		| 'bell-school'
		| 'mobile-screen'
		| 'plane-up'
		| 'folder-heart'
		| 'location-circle'
		| 'face-head-bandage'
		| 'sushi-roll'
		| 'car-bump'
		| 'piggy-bank'
		| 'racquet'
		| 'car-mirrors'
		| 'industry-windows'
		| 'bolt-auto'
		| 'battery-half'
		| 'flux-capacitor'
		| 'mountain-city'
		| 'coins'
		| 'honey-pot'
		| 'olive'
		| 'khanda'
		| 'filter-list'
		| 'outlet'
		| 'sliders'
		| 'cauldron'
		| 'people'
		| 'folder-tree'
		| 'network-wired'
		| 'croissant'
		| 'map-pin'
		| 'hamsa'
		| 'cent-sign'
		| 'swords-laser'
		| 'flask'
		| 'person-pregnant'
		| 'square-u'
		| 'wand-sparkles'
		| 'router'
		| 'ellipsis-vertical'
		| 'sword-laser-alt'
		| 'ticket'
		| 'power-off'
		| 'coin'
		| 'laptop-slash'
		| 'right-long'
		| 'circle-b'
		| 'person-dress-simple'
		| 'pipe-collar'
		| 'lights-holiday'
		| 'citrus'
		| 'flag-usa'
		| 'laptop-file'
		| 'tty'
		| 'chart-tree-map'
		| 'diagram-next'
		| 'person-rifle'
		| 'clock-five-thirty'
		| 'pipe-valve'
		| 'arrow-up-from-arc'
		| 'face-spiral-eyes'
		| 'compress-wide'
		| 'phone-circle-down'
		| 'gear-complex-code'
		| 'house-medical-circle-exclamation'
		| 'badminton'
		| 'closed-captioning'
		| 'person-hiking'
		| 'right-from-line'
		| 'venus-double'
		| 'images'
		| 'calculator'
		| 'shuttlecock'
		| 'user-hair'
		| 'eye-evil'
		| 'people-pulling'
		| 'n'
		| 'garage'
		| 'tram'
		| 'shovel-snow'
		| 'cloud-rain'
		| 'face-lying'
		| 'sprinkler'
		| 'building-circle-xmark'
		| 'sledding'
		| 'game-console-handheld'
		| 'ship'
		| 'clock-six-thirty'
		| 'battery-slash'
		| 'tugrik-sign'
		| 'arrows-down-to-line'
		| 'download'
		| 'shelves'
		| 'cloud-snow'
		| 'grin'
		| 'delete-left'
		| 'oven'
		| 'cloud-binary'
		| 'eyedropper'
		| 'comment-captions'
		| 'comments-question'
		| 'scribble'
		| 'rotate-exclamation'
		| 'file-circle-check'
		| 'glass'
		| 'loader'
		| 'forward'
		| 'user-pilot'
		| 'mobile'
		| 'code-pull-request-closed'
		| 'meh'
		| 'align-center'
		| 'book-skull'
		| 'id-card'
		| 'face-dotted'
		| 'face-worried'
		| 'outdent'
		| 'heart-circle-exclamation'
		| 'house'
		| 'vector-circle'
		| 'car-circle-bolt'
		| 'calendar-week'
		| 'flying-disc'
		| 'laptop-medical'
		| 'square-down-right'
		| 'b'
		| 'seat-airline'
		| 'moon-over-sun'
		| 'pipe'
		| 'file-medical'
		| 'potato'
		| 'dice-one'
		| 'circle-a'
		| 'helmet-battle'
		| 'butter'
		| 'blanket-fire'
		| 'kiwi-bird'
		| 'castle'
		| 'golf-club'
		| 'exchange'
		| 'rotate-right'
		| 'utensils'
		| 'sort-amount-up'
		| 'chart-pie-simple-circle-dollar'
		| 'balloons'
		| 'mill-sign'
		| 'bowl-rice'
		| 'timeline-arrow'
		| 'skull'
		| 'game-board-simple'
		| 'video-circle'
		| 'chart-scatter-bubble'
		| 'house-turret'
		| 'banana'
		| 'hand-holding-skull'
		| 'people-dress'
		| 'loveseat'
		| 'tower-broadcast'
		| 'truck-pickup'
		| 'block-quote'
		| 'up-long'
		| 'stop'
		| 'code-merge'
		| 'money-check-edit-alt'
		| 'up-from-line'
		| 'upload'
		| 'hurricane'
		| 'grid-round-2-plus'
		| 'people-pants'
		| 'mound'
		| 'windsock'
		| 'circle-half'
		| 'brake-warning'
		| 'toilet-portable'
		| 'compact-disc'
		| 'file-download'
		| 'saxophone-fire'
		| 'webcam-slash'
		| 'folder-medical'
		| 'folder-gear'
		| 'hand-wave'
		| 'sort-up-down'
		| 'caravan'
		| 'shield-cat'
		| 'message-slash'
		| 'zap'
		| 'trash-can-check'
		| 'glass-water'
		| 'oil-well'
		| 'person-simple'
		| 'vault'
		| 'mars'
		| 'toilet'
		| 'plane-circle-xmark'
		| 'yen'
		| 'gear-code'
		| 'notes'
		| 'ruble'
		| 'trash-undo'
		| 'glass-champagne'
		| 'objects-align-center-horizontal'
		| 'sun'
		| 'trash-can-slash'
		| 'users-class'
		| 'guitar'
		| 'square-arrow-left'
		| 'square-8'
		| 'face-smile-hearts'
		| 'brackets'
		| 'laptop-arrow-down'
		| 'hockey-stick-puck'
		| 'house-tree'
		| 'signal-fair'
		| 'laugh-wink'
		| 'usd-circle'
		| 'horse-head'
		| 'repeat-alt'
		| 'bore-hole'
		| 'industry'
		| 'image-polaroid'
		| 'wave-triangle'
		| 'person-running-fast'
		| 'circle-down'
		| 'grill'
		| 'arrows-turn-to-dots'
		| 'chart-mixed'
		| 'florin-sign'
		| 'sort-amount-down-alt'
		| 'less-than'
		| 'display-code'
		| 'face-drooling'
		| 'oil-temperature'
		| 'square-question'
		| 'air-conditioner'
		| 'angle-down'
		| 'mountains'
		| 'omega'
		| 'car-tunnel'
		| 'person-dolly-empty'
		| 'pan-food'
		| 'head-side-cough'
		| 'grip-lines'
		| 'thumbs-down'
		| 'user-lock'
		| 'long-arrow-right'
		| 'tickets-airline'
		| 'anchor-circle-xmark'
		| 'ellipsis'
		| 'nfc-slash'
		| 'chess-pawn'
		| 'kit-medical'
		| 'grid-2-plus'
		| 'bells'
		| 'person-through-window'
		| 'toolbox'
		| 'envelope-dot'
		| 'hands-holding-circle'
		| 'bug'
		| 'bowl-chopsticks'
		| 'credit-card'
		| 'circle-s'
		| 'box-ballot'
		| 'car'
		| 'hand-holding-hand'
		| 'user-tie-hair'
		| 'podium-star'
		| 'user-hair-mullet'
		| 'microphone-stand'
		| 'book-reader'
		| 'family-dress'
		| 'circle-x'
		| 'cabin'
		| 'mountain-sun'
		| 'chart-simple-horizontal'
		| 'arrows-left-right-to-line'
		| 'hand-back-point-left'
		| 'messaging'
		| 'file-heart'
		| 'beer-mug'
		| 'dice-d20'
		| 'drone'
		| 'truck-droplet'
		| 'file-circle-xmark'
		| 'temperature-up'
		| 'medal'
		| 'bed'
		| 'book-copy'
		| 'square-h'
		| 'square-c'
		| 'clock-two'
		| 'square-ellipsis-vertical'
		| 'calendar-users'
		| 'podcast'
		| 'bee'
		| 'thermometer-full'
		| 'bell'
		| 'chocolate-bar'
		| 'xmark-large'
		| 'pinata'
		| 'arrows-from-line'
		| 'superscript'
		| 'bowl-spoon'
		| 'hexagon-check'
		| 'plug-circle-xmark'
		| 'star-of-life'
		| 'phone-slash'
		| 'traffic-light-stop'
		| 'paint-roller'
		| 'accent-grave'
		| 'handshake-angle'
		| 'circle-0'
		| 'dial-med-low'
		| 'map-marker-alt'
		| 'crab'
		| 'box-open-full'
		| 'file'
		| 'greater-than'
		| 'quotes'
		| 'pretzel'
		| 'swimmer'
		| 'arrow-down'
		| 'user-robot-xmarks'
		| 'message-quote'
		| 'candy-corn'
		| 'folder-search'
		| 'notebook'
		| 'tint'
		| 'bullseye-pointer'
		| 'eraser'
		| 'hexagon-image'
		| 'globe-americas'
		| 'crate-apple'
		| 'apple-crate'
		| 'person-burst'
		| 'game-board'
		| 'hat-chef'
		| 'hand-back-point-right'
		| 'dove'
		| 'snowflake-droplets'
		| 'battery-empty'
		| 'grid-4'
		| 'socks'
		| 'face-sunglasses'
		| 'inbox'
		| 'square-0'
		| 'section'
		| 'square-this-way-up'
		| 'tachometer-alt'
		| 'square-ampersand'
		| 'envelope-open-text'
		| 'lamp-desk'
		| 'hospital'
		| 'poll-people'
		| 'whiskey-glass-ice'
		| 'wine-bottle'
		| 'chess-rook'
		| 'user-bounty-hunter'
		| 'stream'
		| 'diagram-sankey'
		| 'cloud-hail-mixed'
		| 'circle-up-left'
		| 'dharmachakra'
		| 'objects-align-left'
		| 'oil-can-drip'
		| 'face-smiling-hands'
		| 'broccoli'
		| 'route-interstate'
		| 'ear-muffs'
		| 'hotdog'
		| 'transporter-empty'
		| 'person-walking-with-cane'
		| 'angle-90'
		| 'rectangle-terminal'
		| 'kite'
		| 'drum'
		| 'scrubber'
		| 'ice-cream'
		| 'heart-circle-bolt'
		| 'fish-bones'
		| 'deer-rudolph'
		| 'fax'
		| 'paragraph'
		| 'head-side-heart'
		| 'square-e'
		| 'meter-fire'
		| 'cloud-hail'
		| 'vote-yea'
		| 'money-from-bracket'
		| 'star-half'
		| 'car-bus'
		| 'speaker'
		| 'timer'
		| 'boxes'
		| 'grill-hot'
		| 'ballot-check'
		| 'link'
		| 'ear-listen'
		| 'file-minus'
		| 'tree-city'
		| 'play'
		| 'font'
		| 'cup-togo'
		| 'square-down-left'
		| 'burger-lettuce'
		| 'rupiah-sign'
		| 'search'
		| 'table-tennis'
		| 'person-dots-from-line'
		| 'chevrons-down'
		| 'trash-restore-alt'
		| 'signal-good'
		| 'map-marker-question'
		| 'save-times'
		| 'naira-sign'
		| 'peach'
		| 'taxi-bus'
		| 'bracket-curly'
		| 'lobster'
		| 'dolly-flatbed-empty'
		| 'colon'
		| 'cart-arrow-down'
		| 'wand'
		| 'walkie-talkie'
		| 'file-pen'
		| 'receipt'
		| 'table-picnic'
		| 'square-pen'
		| 'microphone-circle-alt'
		| 'display-slash'
		| 'suitcase-rolling'
		| 'person-circle-exclamation'
		| 'transporter-2'
		| 'hands-holding-diamond'
		| 'money-bill-simple-wave'
		| 'chevron-down'
		| 'battery'
		| 'bell-plus'
		| 'book-arrow-right'
		| 'hospitals'
		| 'club'
		| 'skull-crossbones'
		| 'droplet-degree'
		| 'code-compare'
		| 'list-ul'
		| 'hand-holding-magic'
		| 'watermelon-slice'
		| 'circle-ellipsis'
		| 'school-lock'
		| 'tower-cell'
		| 'sd-cards'
		| 'jug-bottle'
		| 'long-arrow-alt-down'
		| 'envelopes'
		| 'phone-office'
		| 'ranking-star'
		| 'chess-king'
		| 'nfc-pen'
		| 'person-harassing'
		| 'hat-winter'
		| 'brazilian-real-sign'
		| 'landmark-dome'
		| 'bone-break'
		| 'arrow-up'
		| 'down-from-dotted-line'
		| 'tv'
		| 'border-left'
		| 'circle-divide'
		| 'shrimp'
		| 'tasks'
		| 'diagram-subtask'
		| 'jug-detergent'
		| 'user-circle'
		| 'square-y'
		| 'user-doctor-hair'
		| 'planet-ringed'
		| 'mushroom'
		| 'user-shield'
		| 'megaphone'
		| 'wreath-laurel'
		| 'circle-exclamation-check'
		| 'wind'
		| 'box-usd'
		| 'car-crash'
		| 'y'
		| 'user-headset'
		| 'retweet-alt'
		| 'snowboarding'
		| 'square-chevron-right'
		| 'lacrosse-stick-ball'
		| 'truck-fast'
		| 'user-magnifying-glass'
		| 'star-sharp'
		| 'comment-heart'
		| 'circle-1'
		| 'star-circle'
		| 'fish'
		| 'fog'
		| 'waffle'
		| 'music-note'
		| 'hexagon-exclamation'
		| 'cart-shopping-fast'
		| 'object-union'
		| 'user-graduate'
		| 'starfighter'
		| 'circle-half-stroke'
		| 'arrow-right-long-to-line'
		| 'square-arrow-down'
		| 'diamond-half-stroke'
		| 'clapperboard'
		| 'square-chevron-left'
		| 'phone-intercom'
		| 'link-horizontal'
		| 'mango'
		| 'music-note-slash'
		| 'radiation-alt'
		| 'face-tongue-sweat'
		| 'globe-stand'
		| 'baseball'
		| 'circle-p'
		| 'award-simple'
		| 'jet-fighter-up'
		| 'project-diagram'
		| 'pedestal'
		| 'chart-pyramid'
		| 'sidebar'
		| 'snowman-head'
		| 'copy'
		| 'burger-glass'
		| 'volume-xmark'
		| 'hand-sparkles'
		| 'bars-filter'
		| 'paintbrush-pencil'
		| 'party-bell'
		| 'user-vneck-hair'
		| 'jack-o-lantern'
		| 'grip'
		| 'share-square'
		| 'keynote'
		| 'child-rifle'
		| 'gun'
		| 'square-phone'
		| 'hat-beach'
		| 'plus'
		| 'expand'
		| 'computer'
		| 'fort'
		| 'cloud-check'
		| 'xmark'
		| 'face-smirking'
		| 'arrows'
		| 'chalkboard-user'
		| 'rhombus'
		| 'claw-marks'
		| 'peso-sign'
		| 'face-smile-tongue'
		| 'cart-circle-xmark'
		| 'building-shield'
		| 'phone-circle-alt'
		| 'baby'
		| 'users-line'
		| 'quote-left'
		| 'tractor'
		| 'key-skeleton'
		| 'trash-restore'
		| 'arrow-down-up-lock'
		| 'arrow-down-to-bracket'
		| 'lines-leaning'
		| 'square-q'
		| 'ruler-combined'
		| 'symbols'
		| 'copyright'
		| 'flask-gear'
		| 'highlighter-line'
		| 'bracket'
		| 'island-tropical'
		| 'arrow-right-from-line'
		| 'h2'
		| 'equals'
		| 'shortcake'
		| 'peanut'
		| 'wrench-simple'
		| 'blender'
		| 'teeth'
		| 'tally-2'
		| 'sheqel'
		| 'cars'
		| 'axe-battle'
		| 'user-hair-long'
		| 'map'
		| 'file-circle-info'
		| 'face-disappointed'
		| 'lasso-sparkles'
		| 'clock-eleven'
		| 'rocket'
		| 'siren-on'
		| 'clock-ten'
		| 'candle-holder'
		| 'video-arrow-down-left'
		| 'photo-video'
		| 'save-circle-arrow-right'
		| 'folder-minus'
		| 'planet-moon'
		| 'face-eyes-xmarks'
		| 'chart-scatter'
		| 'display-arrow-down'
		| 'store'
		| 'arrow-trend-up'
		| 'plug-circle-minus'
		| 'olive-branch'
		| 'angle'
		| 'vacuum-robot'
		| 'sign'
		| 'square-divide'
		| 'signal-stream-slash'
		| 'bezier-curve'
		| 'eye-dropper-half'
		| 'store-lock'
		| 'bell-slash'
		| 'thunderstorm-sun'
		| 'camera-slash'
		| 'comment-quote'
		| 'tablet'
		| 'school-flag'
		| 'message-code'
		| 'glass-half'
		| 'fill'
		| 'message-minus'
		| 'angle-up'
		| 'dinosaur'
		| 'drumstick-bite'
		| 'link-horizontal-slash'
		| 'holly-berry'
		| 'nose'
		| 'chevron-left'
		| 'bacteria'
		| 'clouds'
		| 'money-bill-simple'
		| 'hand-lizard'
		| 'table-pivot'
		| 'filter-slash'
		| 'trash-undo-alt'
		| 'notdef'
		| 'disease'
		| 'person-to-door'
		| 'turntable'
		| 'briefcase-medical'
		| 'genderless'
		| 'chevron-right'
		| 'signal-weak'
		| 'clock-five'
		| 'retweet'
		| 'car-rear'
		| 'pump-soap'
		| 'computer-classic'
		| 'frame'
		| 'video-slash'
		| 'battery-quarter'
		| 'ellipsis-stroke'
		| 'radio'
		| 'carriage-baby'
		| 'face-expressionless'
		| 'down-to-dotted-line'
		| 'cloud-music'
		| 'traffic-light'
		| 'cloud-minus'
		| 'thermometer'
		| 'shield-minus'
		| 'vr-cardboard'
		| 'car-tilt'
		| 'gauge-circle-minus'
		| 'brightness-low'
		| 'hand-middle-finger'
		| 'percentage'
		| 'truck-moving'
		| 'glass-water-droplet'
		| 'conveyor-belt'
		| 'map-marker-check'
		| 'coin-vertical'
		| 'display'
		| 'person-sign'
		| 'smile'
		| 'phone-hangup'
		| 'signature-slash'
		| 'thumbtack'
		| 'wheat-slash'
		| 'trophy'
		| 'clouds-sun'
		| 'pray'
		| 'hammer'
		| 'face-vomit'
		| 'speakers'
		| 'tty-answer'
		| 'mug-tea-saucer'
		| 'diagram-lean-canvas'
		| 'alt'
		| 'dial'
		| 'hand-peace'
		| 'trash-circle'
		| 'sync-alt'
		| 'circle-quarters'
		| 'spinner'
		| 'tower-control'
		| 'sort-shapes-up'
		| 'whale'
		| 'robot'
		| 'peace'
		| 'party-horn'
		| 'gears'
		| 'sun-bright'
		| 'warehouse'
		| 'conveyor-belt-arm'
		| 'lock-open-alt'
		| 'square-wine-glass-crack'
		| 'arrow-up-right-dots'
		| 'square-n'
		| 'splotch'
		| 'grin-hearts'
		| 'meter'
		| 'mandolin'
		| 'dice-four'
		| 'sim-card'
		| 'transgender'
		| 'mercury'
		| 'up-from-bracket'
		| 'knife-kitchen'
		| 'border-right'
		| 'level-down'
		| 'spade'
		| 'card-spade'
		| 'line-columns'
		| 'arrow-to-right'
		| 'person-falling-burst'
		| 'pennant'
		| 'conveyor-belt-empty'
		| 'user-group-simple'
		| 'award'
		| 'ticket-simple'
		| 'building'
		| 'angles-left'
		| 'video-handheld'
		| 'pancakes'
		| 'album-circle-user'
		| 'qrcode'
		| 'dice-d10'
		| 'fireplace'
		| 'browser'
		| 'pencil-paintbrush'
		| 'fish-cooked'
		| 'chair-office'
		| 'nesting-dolls'
		| 'history'
		| 'trumpet'
		| 'grin-beam-sweat'
		| 'fire-smoke'
		| 'phone-missed'
		| 'file-export'
		| 'shield'
		| 'sort-amount-up-alt'
		| 'repeat-1-alt'
		| 'gun-slash'
		| 'avocado'
		| 'binary'
		| 'glasses-round'
		| 'phone-plus'
		| 'ditto'
		| 'person-seat'
		| 'house-medical'
		| 'golf-ball'
		| 'circle-chevron-left'
		| 'house-chimney-window'
		| 'scythe'
		| 'pen-nib'
		| 'parking-circle-slash'
		| 'tent-arrow-turn-left'
		| 'face-diagonal-mouth'
		| 'diagram-cells'
		| 'cricket'
		| 'tents'
		| 'wand-magic'
		| 'dog'
		| 'pen-line'
		| 'atom-simple'
		| 'ampersand'
		| 'carrot'
		| 'arrow-up-from-line'
		| 'moon'
		| 'pen-slash'
		| 'wine-glass-empty'
		| 'square-star'
		| 'cheese'
		| 'send-backward'
		| 'yin-yang'
		| 'music'
		| 'compass-slash'
		| 'clock-one'
		| 'file-music'
		| 'code-commit'
		| 'temperature-low'
		| 'person-biking'
		| 'display-chart-up-circle-currency'
		| 'skeleton'
		| 'circle-g'
		| 'circle-arrow-up-left'
		| 'coin-blank'
		| 'broom'
		| 'vacuum'
		| 'shield-heart'
		| 'card-heart'
		| 'lightbulb-cfl-on'
		| 'melon'
		| 'gopuram'
		| 'globe-oceania'
		| 'container-storage'
		| 'face-pouting'
		| 'xmark-square'
		| 'face-explode'
		| 'hashtag'
		| 'up-right-and-down-left-from-center'
		| 'oil-can'
		| 't'
		| 'transformer-bolt'
		| 'hippo'
		| 'chart-column'
		| 'vhs'
		| 'infinity'
		| 'vial-circle-check'
		| 'chimney'
		| 'object-intersect'
		| 'person-arrow-down-to-line'
		| 'voicemail'
		| 'wall-brick'
		| 'fan'
		| 'bags-shopping'
		| 'paragraph-rtl'
		| 'person-walking-luggage'
		| 'caravan-simple'
		| 'turtle'
		| 'pencil-mechanical'
		| 'up-down'
		| 'cloud-moon-rain'
		| 'booth-curtain'
		| 'calendar'
		| 'box-heart'
		| 'trailer'
		| 'user-md-chat'
		| 'haykal'
		| 'amp-guitar'
		| 'sd-card'
		| 'volume-slash'
		| 'border-bottom'
		| 'wifi-weak'
		| 'dragon'
		| 'shoe-prints'
		| 'plus-circle'
		| 'grin-tongue-wink'
		| 'hand-holding'
		| 'plug-circle-exclamation'
		| 'unlink'
		| 'clone'
		| 'person-walking-arrow-loop-left'
		| 'sort-alpha-up-alt'
		| 'fire-flame-curved'
		| 'tornado'
		| 'file-circle-plus'
		| 'delete-right'
		| 'quran'
		| 'circle-quarter'
		| 'anchor'
		| 'border-all'
		| 'function'
		| 'face-angry'
		| 'people-simple'
		| 'cookie-bite'
		| 'arrow-trend-down'
		| 'rss'
		| 'face-monocle'
		| 'draw-polygon'
		| 'scale-balanced'
		| 'calendar-note'
		| 'sort-size-down'
		| 'tachometer'
		| 'do-not-enter'
		| 'shower'
		| 'dice-d8'
		| 'desktop'
		| 'm'
		| 'grip-dots-vertical'
		| 'face-viewfinder'
		| 'soft-serve'
		| 'h5'
		| 'hand-back-point-down'
		| 'th-list'
		| 'sms'
		| 'rectangle'
		| 'clipboard-list-check'
		| 'turkey'
		| 'book'
		| 'user-plus'
		| 'ice-skate'
		| 'check'
		| 'battery-three-quarters'
		| 'tomato'
		| 'sword-laser'
		| 'house-circle-check'
		| 'buildings'
		| 'angle-left'
		| 'dolly-flatbed-alt'
		| 'diagram-successor'
		| 'truck-arrow-right'
		| 'square-w'
		| 'arrows-split-up-and-left'
		| 'lamp'
		| 'airplay'
		| 'hand-fist'
		| 'shield-quartered'
		| 'slash-forward'
		| 'map-marker-edit'
		| 'cloud-moon'
		| 'pot-food'
		| 'briefcase'
		| 'person-falling'
		| 'portrait'
		| 'user-tag'
		| 'rug'
		| 'print-slash'
		| 'globe-europe'
		| 'luggage-cart'
		| 'hand-back-point-ribbon'
		| 'window-close'
		| 'tire-rugged'
		| 'lightbulb-dollar'
		| 'cowbell'
		| 'baht-sign'
		| 'corner'
		| 'chevrons-right'
		| 'book-open'
		| 'journal-whills'
		| 'inhaler'
		| 'handcuffs'
		| 'snake'
		| 'warning'
		| 'note-medical'
		| 'database'
		| 'down-left'
		| 'share'
		| 'face-thinking'
		| 'turn-down-right'
		| 'bottle-droplet'
		| 'mask-face'
		| 'hill-rockslide'
		| 'scanner-keyboard'
		| 'circle-o'
		| 'grid-horizontal'
		| 'message-dollar'
		| 'right-left'
		| 'columns-3'
		| 'paper-plane'
		| 'road-circle-exclamation'
		| 'dungeon'
		| 'hand-holding-box'
		| 'input-text'
		| 'window-flip'
		| 'align-right'
		| 'scanner'
		| 'tire'
		| 'engine'
		| 'money-bill-wave-alt'
		| 'life-ring'
		| 'signing'
		| 'circle-caret-right'
		| 'wheat'
		| 'file-spreadsheet'
		| 'audio-description-slash'
		| 'calendar-day'
		| 'water-ladder'
		| 'arrows-v'
		| 'chess-pawn-piece'
		| 'grimace'
		| 'wheelchair-move'
		| 'turn-down'
		| 'square-s'
		| 'rectangle-barcode'
		| 'person-walking-arrow-right'
		| 'square-envelope'
		| 'dice'
		| 'unicorn'
		| 'bowling-ball'
		| 'pompebled'
		| 'brain'
		| 'watch-smart'
		| 'book-user'
		| 'sensor-smoke'
		| 'clapperboard-play'
		| 'bandage'
		| 'calendar-minus'
		| 'xmark-circle'
		| 'circle-4'
		| 'gifts'
		| 'album-collection'
		| 'hotel'
		| 'globe-asia'
		| 'id-card-clip'
		| 'search-plus'
		| 'thumbs-up'
		| 'cloud-showers'
		| 'user-clock'
		| 'onion'
		| 'clock-twelve-thirty'
		| 'arrow-down-to-dotted-line'
		| 'hand-dots'
		| 'file-invoice'
		| 'window-minimize'
		| 'rectangle-wide'
		| 'comment-arrow-up'
		| 'garlic'
		| 'mug-saucer'
		| 'brush'
		| 'tree-decorated'
		| 'mask'
		| 'calendar-heart'
		| 'search-minus'
		| 'flower'
		| 'right-left-large'
		| 'ruler-vertical'
		| 'circles-overlap'
		| 'user-large'
		| 'starship-freighter'
		| 'train-tram'
		| 'bridge-suspension'
		| 'trash-check'
		| 'user-nurse'
		| 'boombox'
		| 'syringe'
		| 'cloud-sun'
		| 'shield-exclamation'
		| 'stopwatch-20'
		| 'square-full'
		| 'grip-dots'
		| 'comment-exclamation'
		| 'pen-swirl'
		| 'falafel'
		| 'circle-2'
		| 'magnet'
		| 'jar'
		| 'gramophone'
		| 'dice-d12'
		| 'sticky-note'
		| 'down'
		| 'hundred-points'
		| 'paperclip-vertical'
		| 'wind-warning'
		| 'map-marker-slash'
		| 'face-sad-sweat'
		| 'bug-slash'
		| 'cupcake'
		| 'light-switch-off'
		| 'toggle-large-off'
		| 'pen-fancy-slash'
		| 'truck-container'
		| 'boot'
		| 'arrow-up-from-water-pump'
		| 'file-check'
		| 'bone'
		| 'cards-blank'
		| 'circle-3'
		| 'bench-tree'
		| 'keyboard-brightness-low'
		| 'ski-boot-ski'
		| 'brain-circuit'
		| 'user-injured'
		| 'firewall'
		| 'sad-tear'
		| 'plane'
		| 'tent-arrows-down'
		| 'exclamation'
		| 'arrows-spin'
		| 'face-smile-relaxed'
		| 'comment-xmark'
		| 'print'
		| 'turkish-lira'
		| 'face-nose-steam'
		| 'waveform-circle'
		| 'usd'
		| 'ferris-wheel'
		| 'computer-speaker'
		| 'skull-cow'
		| 'x'
		| 'search-dollar'
		| 'users-gear'
		| 'person-military-pointing'
		| 'university'
		| 'circle-t'
		| 'sack'
		| 'grid-2'
		| 'cctv'
		| 'umbrella'
		| 'trowel'
		| 'horizontal-rule'
		| 'bed-front'
		| 'd'
		| 'stapler'
		| 'theater-masks'
		| 'kip-sign'
		| 'face-woozy'
		| 'cloud-question'
		| 'pineapple'
		| 'hand-point-left'
		| 'gallery-thumbnails'
		| 'circle-j'
		| 'eyes'
		| 'handshake-simple'
		| 'page-caret-up'
		| 'jet-fighter'
		| 'comet'
		| 'square-share-nodes'
		| 'shield-keyhole'
		| 'barcode'
		| 'plus-minus'
		| 'square-sliders-vertical'
		| 'video'
		| 'message-middle'
		| 'mortar-board'
		| 'hand-holding-medical'
		| 'person-circle-check'
		| 'square-z'
		| 'message-text'
		| 'turn-up'
		| 'monero'
		| 'hooli'
		| 'yelp'
		| 'cc-visa'
		| 'lastfm'
		| 'shopware'
		| 'creative-commons-nc'
		| 'aws'
		| 'redhat'
		| 'yoast'
		| 'cloudflare'
		| 'ups'
		| 'wpexplorer'
		| 'dyalog'
		| 'bity'
		| 'stackpath'
		| 'buysellads'
		| 'first-order'
		| 'modx'
		| 'guilded'
		| 'vnv'
		| 'square-js'
		| 'microsoft'
		| 'qq'
		| 'orcid'
		| 'java'
		| 'invision'
		| 'creative-commons-pd-alt'
		| 'centercode'
		| 'glide-g'
		| 'drupal'
		| 'hire-a-helper'
		| 'creative-commons-by'
		| 'unity'
		| 'whmcs'
		| 'rocketchat'
		| 'vk'
		| 'untappd'
		| 'mailchimp'
		| 'css3-alt'
		| 'square-reddit'
		| 'vimeo-v'
		| 'contao'
		| 'square-font-awesome'
		| 'deskpro'
		| 'sistrix'
		| 'square-instagram'
		| 'battle-net'
		| 'the-red-yeti'
		| 'square-hacker-news'
		| 'edge'
		| 'napster'
		| 'square-snapchat'
		| 'google-plus-g'
		| 'artstation'
		| 'markdown'
		| 'sourcetree'
		| 'google-plus'
		| 'diaspora'
		| 'foursquare'
		| 'stack-overflow'
		| 'github-alt'
		| 'phoenix-squadron'
		| 'pagelines'
		| 'algolia'
		| 'red-river'
		| 'creative-commons-sa'
		| 'safari'
		| 'google'
		| 'square-font-awesome-stroke'
		| 'atlassian'
		| 'linkedin-in'
		| 'digital-ocean'
		| 'nimblr'
		| 'chromecast'
		| 'evernote'
		| 'hacker-news'
		| 'creative-commons-sampling'
		| 'adversal'
		| 'creative-commons'
		| 'watchman-monitoring'
		| 'fonticons'
		| 'weixin'
		| 'shirtsinbulk'
		| 'codepen'
		| 'git-alt'
		| 'lyft'
		| 'rev'
		| 'windows'
		| 'wizards-of-the-coast'
		| 'viadeo-square'
		| 'meetup'
		| 'centos'
		| 'adn'
		| 'cloudsmith'
		| 'pied-piper-alt'
		| 'square-dribbble'
		| 'codiepie'
		| 'node'
		| 'mix'
		| 'steam'
		| 'cc-apple-pay'
		| 'scribd'
		| 'openid'
		| 'instalod'
		| 'expeditedssl'
		| 'sellcast'
		| 'twitter-square'
		| 'r-project'
		| 'delicious'
		| 'freebsd'
		| 'vuejs'
		| 'accusoft'
		| 'ioxhost'
		| 'fonticons-fi'
		| 'app-store'
		| 'cc-mastercard'
		| 'itunes-note'
		| 'golang'
		| 'kickstarter'
		| 'grav'
		| 'weibo'
		| 'uncharted'
		| 'firstdraft'
		| 'youtube-square'
		| 'wikipedia-w'
		| 'wpressr'
		| 'angellist'
		| 'galactic-republic'
		| 'nfc-directional'
		| 'skype'
		| 'joget'
		| 'fedora'
		| 'stripe-s'
		| 'meta'
		| 'laravel'
		| 'hotjar'
		| 'bluetooth-b'
		| 'sticker-mule'
		| 'creative-commons-zero'
		| 'hips'
		| 'behance'
		| 'reddit'
		| 'discord'
		| 'chrome'
		| 'app-store-ios'
		| 'cc-discover'
		| 'wpbeginner'
		| 'confluence'
		| 'mdb'
		| 'dochub'
		| 'accessible-icon'
		| 'ebay'
		| 'amazon'
		| 'unsplash'
		| 'yarn'
		| 'steam-square'
		| '500px'
		| 'vimeo-square'
		| 'asymmetrik'
		| 'font-awesome'
		| 'gratipay'
		| 'apple'
		| 'hive'
		| 'gitkraken'
		| 'keybase'
		| 'apple-pay'
		| 'padlet'
		| 'amazon-pay'
		| 'square-github'
		| 'stumbleupon'
		| 'fedex'
		| 'phoenix-framework'
		| 'shopify'
		| 'neos'
		| 'hackerrank'
		| 'researchgate'
		| 'swift'
		| 'angular'
		| 'speakap'
		| 'angrycreative'
		| 'y-combinator'
		| 'empire'
		| 'envira'
		| 'square-gitlab'
		| 'studiovinari'
		| 'pied-piper'
		| 'wordpress'
		| 'product-hunt'
		| 'firefox'
		| 'linode'
		| 'goodreads'
		| 'square-odnoklassniki'
		| 'jsfiddle'
		| 'sith'
		| 'themeisle'
		| 'page4'
		| 'hashnode'
		| 'react'
		| 'cc-paypal'
		| 'squarespace'
		| 'cc-stripe'
		| 'creative-commons-share'
		| 'bitcoin'
		| 'keycdn'
		| 'opera'
		| 'itch-io'
		| 'umbraco'
		| 'galactic-senate'
		| 'ubuntu'
		| 'draft2digital'
		| 'stripe'
		| 'houzz'
		| 'gg'
		| 'dhl'
		| 'square-pinterest'
		| 'xing'
		| 'blackberry'
		| 'creative-commons-pd'
		| 'playstation'
		| 'quinscape'
		| 'less'
		| 'blogger-b'
		| 'opencart'
		| 'vine'
		| 'paypal'
		| 'gitlab'
		| 'typo3'
		| 'reddit-alien'
		| 'yahoo'
		| 'dailymotion'
		| 'affiliatetheme'
		| 'pied-piper-pp'
		| 'bootstrap'
		| 'odnoklassniki'
		| 'nfc-symbol'
		| 'ethereum'
		| 'speaker-deck'
		| 'creative-commons-nc-eu'
		| 'patreon'
		| 'avianex'
		| 'ello'
		| 'gofore'
		| 'bimobject'
		| 'facebook-f'
		| 'square-google-plus'
		| 'mandalorian'
		| 'first-order-alt'
		| 'osi'
		| 'google-wallet'
		| 'd-and-d-beyond'
		| 'periscope'
		| 'fulcrum'
		| 'cloudscale'
		| 'forumbee'
		| 'mizuni'
		| 'schlix'
		| 'xing-square'
		| 'bandcamp'
		| 'wpforms'
		| 'cloudversify'
		| 'usps'
		| 'megaport'
		| 'magento'
		| 'spotify'
		| 'optin-monster'
		| 'fly'
		| 'aviato'
		| 'itunes'
		| 'cuttlefish'
		| 'blogger'
		| 'flickr'
		| 'viber'
		| 'soundcloud'
		| 'digg'
		| 'tencent-weibo'
		| 'symfony'
		| 'maxcdn'
		| 'etsy'
		| 'facebook-messenger'
		| 'audible'
		| 'think-peaks'
		| 'bilibili'
		| 'erlang'
		| 'cotton-bureau'
		| 'dashcube'
		| 'innosoft'
		| 'stack-exchange'
		| 'elementor'
		| 'square-pied-piper'
		| 'creative-commons-nd'
		| 'palfed'
		| 'superpowers'
		| 'resolving'
		| 'xbox'
		| 'searchengin'
		| 'tiktok'
		| 'square-facebook'
		| 'renren'
		| 'linux'
		| 'glide'
		| 'linkedin'
		| 'hubspot'
		| 'deploydog'
		| 'twitch'
		| 'ravelry'
		| 'mixer'
		| 'square-lastfm'
		| 'vimeo'
		| 'mendeley'
		| 'uniregistry'
		| 'figma'
		| 'creative-commons-remix'
		| 'cc-amazon-pay'
		| 'dropbox'
		| 'instagram'
		| 'cmplid'
		| 'facebook'
		| 'gripfire'
		| 'jedi-order'
		| 'uikit'
		| 'fort-awesome-alt'
		| 'phabricator'
		| 'ussunnah'
		| 'earlybirds'
		| 'trade-federation'
		| 'autoprefixer'
		| 'whatsapp'
		| 'slideshare'
		| 'google-play'
		| 'viadeo'
		| 'line'
		| 'google-drive'
		| 'servicestack'
		| 'simplybuilt'
		| 'bitbucket'
		| 'imdb'
		| 'deezer'
		| 'raspberry-pi'
		| 'jira'
		| 'docker'
		| 'screenpal'
		| 'bluetooth'
		| 'gitter'
		| 'd-and-d'
		| 'microblog'
		| 'cc-diners-club'
		| 'gg-circle'
		| 'pied-piper-hat'
		| 'kickstarter-k'
		| 'yandex'
		| 'readme'
		| 'html5'
		| 'sellsy'
		| 'sass'
		| 'wsh'
		| 'buromobelexperte'
		| 'salesforce'
		| 'octopus-deploy'
		| 'medapps'
		| 'ns8'
		| 'pinterest-p'
		| 'apper'
		| 'fort-awesome'
		| 'waze'
		| 'cc-jcb'
		| 'snapchat'
		| 'fantasy-flight-games'
		| 'rust'
		| 'wix'
		| 'square-behance'
		| 'supple'
		| 'rebel'
		| 'css3'
		| 'staylinked'
		| 'kaggle'
		| 'space-awesome'
		| 'deviantart'
		| 'cpanel'
		| 'goodreads-g'
		| 'square-git'
		| 'tumblr-square'
		| 'trello'
		| 'creative-commons-nc-jp'
		| 'get-pocket'
		| 'perbyte'
		| 'grunt'
		| 'weebly'
		| 'connectdevelop'
		| 'leanpub'
		| 'black-tie'
		| 'themeco'
		| 'python'
		| 'android'
		| 'bots'
		| 'free-code-camp'
		| 'hornbill'
		| 'js'
		| 'ideal'
		| 'git'
		| 'dev'
		| 'sketch'
		| 'yandex-international'
		| 'cc-amex'
		| 'uber'
		| 'github'
		| 'php'
		| 'alipay'
		| 'youtube'
		| 'skyatlas'
		| 'firefox-browser'
		| 'replyd'
		| 'suse'
		| 'jenkins'
		| 'twitter'
		| 'rockrms'
		| 'pinterest'
		| 'buffer'
		| 'npm'
		| 'yammer'
		| 'btc'
		| 'dribbble'
		| 'stumbleupon-circle'
		| 'internet-explorer'
		| 'stubber'
		| 'telegram'
		| 'old-republic'
		| 'odysee'
		| 'whatsapp-square'
		| 'node-js'
		| 'edge-legacy'
		| 'slack'
		| 'medrt'
		| 'usb'
		| 'tumblr'
		| 'vaadin'
		| 'quora'
		| 'reacteurope'
		| 'medium'
		| 'amilia'
		| 'mixcloud'
		| 'flipboard'
		| 'viacoin'
		| 'critical-role'
		| 'sitrox'
		| 'discourse'
		| 'joomla'
		| 'mastodon'
		| 'airbnb'
		| 'wolf-pack-battalion'
		| 'buy-n-large'
		| 'gulp'
		| 'creative-commons-sampling-plus'
		| 'strava'
		| 'ember'
		| 'canadian-maple-leaf'
		| 'teamspeak'
		| 'pushed'
		| 'wordpress-simple'
		| 'nutritionix'
		| 'wodu'
		| 'google-pay'
		| 'intercom'
		| 'zhihu'
		| 'korvue'
		| 'pix'
		| 'steam-symbol'
}
