#! /bin/bash

for src in dist/packs/*/; do
	pack=${src%*/} # remove the trailing "/"
	pack=${pack##*/} # get everything after the final "/"
	fvtt package --id foundry-ironsworn --type System unpack ${pack} -c --json --in "dist/packs" --out "json-packs/${pack}"
done
